# Translations template for nova.
# Copyright (C) 2012 ORGANIZATION
# This file is distributed under the same license as the nova project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2012.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova 2013.1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2012-11-03 00:01+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.6\n"

#: nova/context.py:62
#, python-format
msgid "Arguments dropped when creating context: %s"
msgstr ""

#: nova/context.py:100
#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr ""

#: nova/crypto.py:47
msgid "Filename of root CA"
msgstr ""

#: nova/crypto.py:50
msgid "Filename of private key"
msgstr ""

#: nova/crypto.py:53
msgid "Filename of root Certificate Revocation List"
msgstr ""

#: nova/crypto.py:56
msgid "Where we keep our keys"
msgstr ""

#: nova/crypto.py:59
msgid "Where we keep our root CA"
msgstr ""

#: nova/crypto.py:62
msgid "Should we use a CA for each project?"
msgstr ""

#: nova/crypto.py:66
#, python-format
msgid "Subject for certificate for users, %s for project, user, timestamp"
msgstr ""

#: nova/crypto.py:71
#, python-format
msgid "Subject for certificate for projects, %s for project, timestamp"
msgstr ""

#: nova/crypto.py:301
#, python-format
msgid "Flags path: %s"
msgstr ""

#: nova/exception.py:56
msgid "Unexpected error while running command."
msgstr ""

#: nova/exception.py:59
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: nova/exception.py:72
msgid "DB exception wrapped."
msgstr ""

#: nova/exception.py:131
msgid "An unknown exception occurred."
msgstr ""

#: nova/exception.py:152 nova/openstack/common/rpc/common.py:46
msgid "Exception in string format operation"
msgstr ""

#: nova/exception.py:162
msgid "Unknown"
msgstr ""

#: nova/exception.py:179
msgid "Failed to decrypt text"
msgstr ""

#: nova/exception.py:183
msgid "Virtual Interface creation failed"
msgstr ""

#: nova/exception.py:187
msgid "5 attempts to create virtual interfacewith unique mac address failed"
msgstr ""

#: nova/exception.py:192
#, python-format
msgid "Connection to glance host %(host)s:%(port)s failed: %(reason)s"
msgstr ""

#: nova/exception.py:197
msgid "Not authorized."
msgstr ""

#: nova/exception.py:202
msgid "User does not have admin privileges"
msgstr ""

#: nova/exception.py:206
#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr ""

#: nova/exception.py:210
#, python-format
msgid "Image %(image_id)s is not active."
msgstr ""

#: nova/exception.py:214
#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr ""

#: nova/exception.py:218
msgid "Unacceptable parameters."
msgstr ""

#: nova/exception.py:223
msgid "Invalid snapshot"
msgstr ""

#: nova/exception.py:227
#, python-format
msgid "Volume %(volume_id)s is not attached to anything"
msgstr ""

#: nova/exception.py:231
#, python-format
msgid "Volume %(volume_id)s is still attached, detach volume first."
msgstr ""

#: nova/exception.py:235 nova/api/ec2/cloud.py:389 nova/api/ec2/cloud.py:414
#: nova/api/openstack/compute/contrib/keypairs.py:98 nova/compute/api.py:2234
msgid "Keypair data is invalid"
msgstr ""

#: nova/exception.py:239
msgid "Failed to load data into json format"
msgstr ""

#: nova/exception.py:243
msgid "The request is invalid."
msgstr ""

#: nova/exception.py:247
msgid "Invalid input received"
msgstr ""

#: nova/exception.py:251
msgid "Invalid volume type"
msgstr ""

#: nova/exception.py:255
msgid "Invalid volume"
msgstr ""

#: nova/exception.py:259 nova/api/openstack/compute/servers.py:1283
#: nova/api/openstack/compute/contrib/admin_actions.py:242
msgid "Invalid metadata"
msgstr ""

#: nova/exception.py:263
msgid "Invalid metadata size"
msgstr ""

#: nova/exception.py:267
#, python-format
msgid "Invalid port range %(from_port)s:%(to_port)s. %(msg)s"
msgstr ""

#: nova/exception.py:271 nova/api/ec2/cloud.py:571
#, python-format
msgid "Invalid IP protocol %(protocol)s."
msgstr ""

#: nova/exception.py:275
#, python-format
msgid "Invalid content type %(content_type)s."
msgstr ""

#: nova/exception.py:279
#, python-format
msgid "Invalid cidr %(cidr)s."
msgstr ""

#: nova/exception.py:283
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: nova/exception.py:290
#, python-format
msgid "%(err)s"
msgstr ""

#: nova/exception.py:294
#, python-format
msgid ""
"Cannot perform action '%(action)s' on aggregate %(aggregate_id)s. Reason:"
" %(reason)s."
msgstr ""

#: nova/exception.py:299
#, python-format
msgid "Group not valid. Reason: %(reason)s"
msgstr ""

#: nova/exception.py:303
msgid "Sort key supplied was not valid."
msgstr ""

#: nova/exception.py:307
#, python-format
msgid ""
"Instance %(instance_uuid)s in %(attr)s %(state)s. Cannot %(method)s while"
" the instance is in this state."
msgstr ""

#: nova/exception.py:312
#, python-format
msgid "Instance %(instance_id)s is not running."
msgstr ""

#: nova/exception.py:316
#, python-format
msgid "Instance %(instance_id)s is not in rescue mode"
msgstr ""

#: nova/exception.py:320
#, python-format
msgid "Instance %(instance_id)s is not ready"
msgstr ""

#: nova/exception.py:324
msgid "Failed to suspend instance"
msgstr ""

#: nova/exception.py:328
msgid "Failed to resume server"
msgstr ""

#: nova/exception.py:332
msgid "Failed to reboot instance"
msgstr ""

#: nova/exception.py:336
msgid "Failed to terminate instance"
msgstr ""

#: nova/exception.py:340
msgid "Service is unavailable at this time."
msgstr ""

#: nova/exception.py:344
msgid "Insufficient compute resources."
msgstr ""

#: nova/exception.py:348
msgid "Compute service is unavailable at this time."
msgstr ""

#: nova/exception.py:352
#, python-format
msgid "Unable to migrate instance (%(instance_id)s) to current host (%(host)s)."
msgstr ""

#: nova/exception.py:357
msgid "The supplied hypervisor type of is invalid."
msgstr ""

#: nova/exception.py:361
msgid "The instance requires a newer hypervisor version than has been provided."
msgstr ""

#: nova/exception.py:366
#, python-format
msgid ""
"The supplied disk path (%(path)s) already exists, it is expected not to "
"exist."
msgstr ""

#: nova/exception.py:371
#, python-format
msgid "The supplied device path (%(path)s) is invalid."
msgstr ""

#: nova/exception.py:375
#, python-format
msgid "The supplied device path (%(path)s) is in use."
msgstr ""

#: nova/exception.py:379
#, python-format
msgid "The supplied device (%(device)s) is busy."
msgstr ""

#: nova/exception.py:383
msgid "Unacceptable CPU info"
msgstr ""

#: nova/exception.py:387
#, python-format
msgid "%(address)s is not a valid IP v4/6 address."
msgstr ""

#: nova/exception.py:391
#, python-format
msgid ""
"VLAN tag is not appropriate for the port group %(bridge)s. Expected VLAN "
"tag is %(tag)s, but the one associated with the port group is %(pgroup)s."
msgstr ""

#: nova/exception.py:397
#, python-format
msgid ""
"vSwitch which contains the port group %(bridge)s is not associated with "
"the desired physical adapter. Expected vSwitch is %(expected)s, but the "
"one associated is %(actual)s."
msgstr ""

#: nova/exception.py:404
#, python-format
msgid "Disk format %(disk_format)s is not acceptable"
msgstr ""

#: nova/exception.py:408
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr ""

#: nova/exception.py:412
#, python-format
msgid "Instance %(instance_id)s is unacceptable: %(reason)s"
msgstr ""

#: nova/exception.py:416
#, python-format
msgid "Ec2 id %(ec2_id)s is unacceptable."
msgstr ""

#: nova/exception.py:420
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr ""

#: nova/exception.py:424
msgid "Constraint not met."
msgstr ""

#: nova/exception.py:429
msgid "Resource could not be found."
msgstr ""

#: nova/exception.py:434
#, python-format
msgid "Could not find driver for compute_driver %(name)s"
msgstr ""

#: nova/exception.py:438
#, python-format
msgid "Volume %(volume_id)s persistence file could not be found."
msgstr ""

#: nova/exception.py:442
#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr ""

#: nova/exception.py:446
#, python-format
msgid "Unable to locate account %(account_name)s on Solidfire device"
msgstr ""

#: nova/exception.py:451
#, python-format
msgid "Volume %(volume_id)s has no metadata with key %(metadata_key)s."
msgstr ""

#: nova/exception.py:456
#, python-format
msgid "Volume type %(volume_type_id)s could not be found."
msgstr ""

#: nova/exception.py:460
#, python-format
msgid "Volume type with name %(volume_type_name)s could not be found."
msgstr ""

#: nova/exception.py:465
#, python-format
msgid ""
"Volume Type %(volume_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr ""

#: nova/exception.py:470
#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr ""

#: nova/exception.py:474
#, python-format
msgid "deleting volume %(volume_name)s that has snapshot"
msgstr ""

#: nova/exception.py:478
#, python-format
msgid "deleting snapshot %(snapshot_name)s that has dependent volumes"
msgstr ""

#: nova/exception.py:483
#, python-format
msgid "No target id found for volume %(volume_id)s."
msgstr ""

#: nova/exception.py:487
#, python-format
msgid "Failed to create iscsi target for volume %(volume_id)s."
msgstr ""

#: nova/exception.py:491
#, python-format
msgid "Failed to remove iscsi target for volume %(volume_id)s."
msgstr ""

#: nova/exception.py:495
#, python-format
msgid "No disk at %(location)s"
msgstr ""

#: nova/exception.py:499
#, python-format
msgid "Could not find a handler for %(driver_type)s volume."
msgstr ""

#: nova/exception.py:503
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr ""

#: nova/exception.py:507
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr ""

#: nova/exception.py:511
#, python-format
msgid ""
"Image %(image_id)s could not be found. The nova EC2 API assigns image ids"
" dynamically when they are listed for the first time. Have you listed "
"image ids since adding this image?"
msgstr ""

#: nova/exception.py:518
#, python-format
msgid "Project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:522
msgid "Cannot find SR to read/write VDI."
msgstr ""

#: nova/exception.py:526
#, python-format
msgid "Network %(network_id)s is still in use."
msgstr ""

#: nova/exception.py:530
#, python-format
msgid "%(req)s is required to create a network."
msgstr ""

#: nova/exception.py:534
#, python-format
msgid "Network %(network_id)s could not be found."
msgstr ""

#: nova/exception.py:538
#, python-format
msgid "Network could not be found for bridge %(bridge)s"
msgstr ""

#: nova/exception.py:542
#, python-format
msgid "Network could not be found for uuid %(uuid)s"
msgstr ""

#: nova/exception.py:546
#, python-format
msgid "Network could not be found with cidr %(cidr)s."
msgstr ""

#: nova/exception.py:550
#, python-format
msgid "Network could not be found for instance %(instance_id)s."
msgstr ""

#: nova/exception.py:554
msgid "No networks defined."
msgstr ""

#: nova/exception.py:558
#, python-format
msgid ""
"Either Network uuid %(network_uuid)s is not present or is not assigned to"
" the project %(project_id)s."
msgstr ""

#: nova/exception.py:563
#, python-format
msgid "Host is not set to the network (%(network_id)s)."
msgstr ""

#: nova/exception.py:567
msgid "Could not find the datastore reference(s) which the VM uses."
msgstr ""

#: nova/exception.py:571
#, python-format
msgid "Port %(port_id)s is still in use."
msgstr ""

#: nova/exception.py:575
#, python-format
msgid "Port %(port_id)s could not be found."
msgstr ""

#: nova/exception.py:579
#, python-format
msgid "No fixed IP associated with id %(id)s."
msgstr ""

#: nova/exception.py:583
#, python-format
msgid "Fixed ip not found for address %(address)s."
msgstr ""

#: nova/exception.py:587
#, python-format
msgid "Instance %(instance_uuid)s has zero fixed ips."
msgstr ""

#: nova/exception.py:591
#, python-format
msgid "Network host %(host)s has zero fixed ips in network %(network_id)s."
msgstr ""

#: nova/exception.py:596
#, python-format
msgid "Instance %(instance_uuid)s doesn't have fixed ip '%(ip)s'."
msgstr ""

#: nova/exception.py:600
#, python-format
msgid ""
"Fixed IP address (%(address)s) does not exist in network "
"(%(network_uuid)s)."
msgstr ""

#: nova/exception.py:605
#, python-format
msgid ""
"Fixed IP address %(address)s is already in use on instance "
"%(instance_uuid)s."
msgstr ""

#: nova/exception.py:610
#, python-format
msgid "More than one instance is associated with fixed ip address '%(address)s'."
msgstr ""

#: nova/exception.py:615
#, python-format
msgid "Fixed IP address %(address)s is invalid."
msgstr ""

#: nova/exception.py:619
msgid "Zero fixed ips available."
msgstr ""

#: nova/exception.py:623
msgid "Zero fixed ips could be found."
msgstr ""

#: nova/exception.py:632
#, python-format
msgid "Floating ip %(address)s already exists."
msgstr ""

#: nova/exception.py:636
#, python-format
msgid "Floating ip not found for id %(id)s."
msgstr ""

#: nova/exception.py:640
#, python-format
msgid "The DNS entry %(name)s already exists in domain %(domain)s."
msgstr ""

#: nova/exception.py:644
#, python-format
msgid "Floating ip not found for address %(address)s."
msgstr ""

#: nova/exception.py:648
#, python-format
msgid "Floating ip not found for host %(host)s."
msgstr ""

#: nova/exception.py:652
#, python-format
msgid "Multiple floating ips are found for address %(address)s."
msgstr ""

#: nova/exception.py:656
msgid "Floating ip pool not found."
msgstr ""

#: nova/exception.py:661
msgid "Zero floating ips available."
msgstr ""

#: nova/exception.py:666
#, python-format
msgid "Floating ip %(address)s is associated."
msgstr ""

#: nova/exception.py:670
#, python-format
msgid "Floating ip %(address)s is not associated."
msgstr ""

#: nova/exception.py:674
msgid "Zero floating ips exist."
msgstr ""

#: nova/exception.py:678
#, python-format
msgid "Interface %(interface)s not found."
msgstr ""

#: nova/exception.py:682
msgid "Cannot disassociate auto assigined floating ip"
msgstr ""

#: nova/exception.py:686
#, python-format
msgid "Keypair %(name)s not found for user %(user_id)s"
msgstr ""

#: nova/exception.py:690
#, python-format
msgid "Certificate %(certificate_id)s not found."
msgstr ""

#: nova/exception.py:694
#, python-format
msgid "Service %(service_id)s could not be found."
msgstr ""

#: nova/exception.py:698
#, python-format
msgid "Host %(host)s could not be found."
msgstr ""

#: nova/exception.py:702
#, python-format
msgid "Compute host %(host)s could not be found."
msgstr ""

#: nova/exception.py:706
#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr ""

#: nova/exception.py:710
#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr ""

#: nova/exception.py:714
#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: "
"%(unders)s"
msgstr ""

#: nova/exception.py:719
msgid "Quota could not be found"
msgstr ""

#: nova/exception.py:723
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: nova/exception.py:727
#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:731
#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr ""

#: nova/exception.py:735
#, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:739
#, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr ""

#: nova/exception.py:743
#, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr ""

#: nova/exception.py:747
#, python-format
msgid "Security group %(security_group_id)s not found."
msgstr ""

#: nova/exception.py:751
#, python-format
msgid "Security group %(security_group_id)s not found for project %(project_id)s."
msgstr ""

#: nova/exception.py:756
#, python-format
msgid "Security group with rule %(rule_id)s not found."
msgstr ""

#: nova/exception.py:760
#, python-format
msgid ""
"Security group %(security_group_id)s is already associated with the "
"instance %(instance_id)s"
msgstr ""

#: nova/exception.py:765
#, python-format
msgid ""
"Security group %(security_group_id)s is not associated with the instance "
"%(instance_id)s"
msgstr ""

#: nova/exception.py:770
#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr ""

#: nova/exception.py:774
#, python-format
msgid "Migration not found for instance %(instance_id)s with status %(status)s."
msgstr ""

#: nova/exception.py:779
#, python-format
msgid "Console pool %(pool_id)s could not be found."
msgstr ""

#: nova/exception.py:783
#, python-format
msgid ""
"Console pool of type %(console_type)s for compute host %(compute_host)s "
"on proxy host %(host)s not found."
msgstr ""

#: nova/exception.py:789
#, python-format
msgid "Console %(console_id)s could not be found."
msgstr ""

#: nova/exception.py:793
#, python-format
msgid "Console for instance %(instance_uuid)s could not be found."
msgstr ""

#: nova/exception.py:797
#, python-format
msgid ""
"Console for instance %(instance_uuid)s in pool %(pool_id)s could not be "
"found."
msgstr ""

#: nova/exception.py:802
#, python-format
msgid "Invalid console type %(console_type)s "
msgstr ""

#: nova/exception.py:806
#, python-format
msgid "Instance type %(instance_type_id)s could not be found."
msgstr ""

#: nova/exception.py:810
#, python-format
msgid "Instance type with name %(instance_type_name)s could not be found."
msgstr ""

#: nova/exception.py:815
#, python-format
msgid "Flavor %(flavor_id)s could not be found."
msgstr ""

#: nova/exception.py:819
#, python-format
msgid "Flavor access not found for %(flavor_id) / %(project_id) combination."
msgstr ""

#: nova/exception.py:824
#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr ""

#: nova/exception.py:828
#, python-format
msgid "Scheduler cost function %(cost_fn_str)s could not be found."
msgstr ""

#: nova/exception.py:833
#, python-format
msgid "Scheduler weight flag not found: %(flag_name)s"
msgstr ""

#: nova/exception.py:837
#, python-format
msgid "Instance %(instance_uuid)s has no metadata with key %(metadata_key)s."
msgstr ""

#: nova/exception.py:842
#, python-format
msgid ""
"Instance %(instance_uuid)s has no system metadata with key "
"%(metadata_key)s."
msgstr ""

#: nova/exception.py:847
#, python-format
msgid ""
"Instance Type %(instance_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr ""

#: nova/exception.py:852
#, python-format
msgid "File %(file_path)s could not be found."
msgstr ""

#: nova/exception.py:856
msgid "Zero files could be found."
msgstr ""

#: nova/exception.py:860
#, python-format
msgid "Virtual switch associated with the network adapter %(adapter)s not found."
msgstr ""

#: nova/exception.py:865
#, python-format
msgid "Network adapter %(adapter)s could not be found."
msgstr ""

#: nova/exception.py:869
#, python-format
msgid "Class %(class_name)s could not be found: %(exception)s"
msgstr ""

#: nova/exception.py:873
msgid "Action not allowed."
msgstr ""

#: nova/exception.py:877
msgid "Rotation is not allowed for snapshots"
msgstr ""

#: nova/exception.py:881
msgid "Rotation param is required for backup image_type"
msgstr ""

#: nova/exception.py:885
#, python-format
msgid "Key pair %(key_name)s already exists."
msgstr ""

#: nova/exception.py:889
#, python-format
msgid "Instance %(name)s already exists."
msgstr ""

#: nova/exception.py:893
#, python-format
msgid "Instance Type with name %(name)s already exists."
msgstr ""

#: nova/exception.py:897
#, python-format
msgid "Instance Type with ID %(flavor_id)s already exists."
msgstr ""

#: nova/exception.py:901
#, python-format
msgid ""
"Flavor access alreay exists for flavor %(flavor_id)s and project "
"%(project_id)s combination."
msgstr ""

#: nova/exception.py:906
#, python-format
msgid "Volume Type %(name)s already exists."
msgstr ""

#: nova/exception.py:910
#, python-format
msgid "%(path)s is not on shared storage: %(reason)s"
msgstr ""

#: nova/exception.py:914
#, python-format
msgid "%(path)s is not on local storage: %(reason)s"
msgstr ""

#: nova/exception.py:918
msgid "Migration error"
msgstr ""

#: nova/exception.py:922
#, python-format
msgid "Malformed message body: %(reason)s"
msgstr ""

#: nova/exception.py:928
#, python-format
msgid "Could not find config at %(path)s"
msgstr ""

#: nova/exception.py:932
#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s"
msgstr ""

#: nova/exception.py:936
msgid "When resizing, instances must change flavor!"
msgstr ""

#: nova/exception.py:940
msgid "Image is larger than instance type allows"
msgstr ""

#: nova/exception.py:944
msgid "Instance type's memory is too small for requested image."
msgstr ""

#: nova/exception.py:948
msgid "Instance type's disk is too small for requested image."
msgstr ""

#: nova/exception.py:952
#, python-format
msgid "Insufficient free memory on compute node to start %(uuid)s."
msgstr ""

#: nova/exception.py:956
msgid "Could not fetch bandwidth/cpu/disk metrics for this host."
msgstr ""

#: nova/exception.py:960
#, python-format
msgid "No valid host was found. %(reason)s"
msgstr ""

#: nova/exception.py:964
#, python-format
msgid "Host %(host)s is not up or doesn't exist."
msgstr ""

#: nova/exception.py:968
msgid "Quota exceeded"
msgstr ""

#: nova/exception.py:975
#, python-format
msgid ""
"Quota exceeded for %(overs)s: Requested %(req)s, but already used "
"%(used)d of %(allowed)d %(resource)s"
msgstr ""

#: nova/exception.py:980
msgid "Maximum volume size exceeded"
msgstr ""

#: nova/exception.py:984
#, python-format
msgid "Maximum number of volumes allowed (%(allowed)d) exceeded"
msgstr ""

#: nova/exception.py:988
msgid "Maximum number of floating ips exceeded"
msgstr ""

#: nova/exception.py:992
#, python-format
msgid "Maximum number of metadata items exceeds %(allowed)d"
msgstr ""

#: nova/exception.py:996
msgid "Personality file limit exceeded"
msgstr ""

#: nova/exception.py:1000
msgid "Personality file path too long"
msgstr ""

#: nova/exception.py:1004
msgid "Personality file content too long"
msgstr ""

#: nova/exception.py:1008
msgid "Maximum number of key pairs exceeded"
msgstr ""

#: nova/exception.py:1012
msgid "Maximum number of security groups or rules exceeded"
msgstr ""

#: nova/exception.py:1016
#, python-format
msgid ""
"Aggregate %(aggregate_id)s: action '%(action)s' caused an error: "
"%(reason)s."
msgstr ""

#: nova/exception.py:1021
#, python-format
msgid "Aggregate %(aggregate_id)s could not be found."
msgstr ""

#: nova/exception.py:1025
#, python-format
msgid "Aggregate %(aggregate_name)s already exists."
msgstr ""

#: nova/exception.py:1029
#, python-format
msgid "Aggregate %(aggregate_id)s has no host %(host)s."
msgstr ""

#: nova/exception.py:1033
#, python-format
msgid "Aggregate %(aggregate_id)s has no metadata with key %(metadata_key)s."
msgstr ""

#: nova/exception.py:1038
#, python-format
msgid "Aggregate %(aggregate_id)s already has host %(host)s."
msgstr ""

#: nova/exception.py:1042
#, python-format
msgid "Detected more than one volume with name %(vol_name)s"
msgstr ""

#: nova/exception.py:1046
#, python-format
msgid "Cannot create volume_type with name %(name)s and specs %(extra_specs)s"
msgstr ""

#: nova/exception.py:1051
#, python-format
msgid "Bad or unexpected response from the storage volume backend API: %(data)s"
msgstr ""

#: nova/exception.py:1056
msgid "Unknown NFS exception"
msgstr ""

#: nova/exception.py:1060
msgid "No mounted NFS shares found"
msgstr ""

#: nova/exception.py:1064
#, python-format
msgid "There is no share which can host %(volume_size)sG"
msgstr ""

#: nova/exception.py:1068
msgid "Unable to create instance type"
msgstr ""

#: nova/exception.py:1072
#, python-format
msgid "Failed to set admin password on %(instance)s because %(reason)s"
msgstr ""

#: nova/exception.py:1078
msgid "Bad response from SolidFire API"
msgstr ""

#: nova/exception.py:1082
#, python-format
msgid "Error in SolidFire API response: data=%(data)s"
msgstr ""

#: nova/exception.py:1086
#, python-format
msgid "Detected existing vlan with id %(vlan)d"
msgstr ""

#: nova/exception.py:1090
#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr ""

#: nova/exception.py:1094
#, python-format
msgid "Marker %(marker)s could not be found."
msgstr ""

#: nova/exception.py:1098
#, python-format
msgid "Invalid id: %(val)s (expecting \"i-...\")."
msgstr ""

#: nova/exception.py:1102
#, python-format
msgid "Could not fetch image %(image_id)s"
msgstr ""

#: nova/exception.py:1106
#, python-format
msgid "Task %(task_name)s is already running on host %(host)s"
msgstr ""

#: nova/exception.py:1110
#, python-format
msgid "Task %(task_name)s is not running on host %(host)s"
msgstr ""

#: nova/exception.py:1114
#, python-format
msgid "Instance %(instance_uuid)s is locked"
msgstr ""

#: nova/exception.py:1118
#, python-format
msgid "Could not mount vfat config drive. %(operation)s failed. Error: %(error)s"
msgstr ""

#: nova/exception.py:1123
#, python-format
msgid "Unknown config drive format %(format)s. Select one of iso9660 or vfat."
msgstr ""

#: nova/exception.py:1128
#, python-format
msgid ""
"User data too large. User data must be no larger than %(maxsize)s bytes "
"once base64 encoded. Your data is %(length)d bytes"
msgstr ""

#: nova/exception.py:1134
msgid "User data needs to be valid base 64."
msgstr ""

#: nova/exception.py:1138
#, python-format
msgid ""
"unexpected task state: expecting %(expected)s but the actual state is "
"%(actual)s"
msgstr ""

#: nova/exception.py:1143
#, python-format
msgid "The CA file for %(project)s could not be found"
msgstr ""

#: nova/exception.py:1147
#, python-format
msgid "The CRL file for %(project)s could not be found"
msgstr ""

#: nova/manager.py:166
#, python-format
msgid "Skipping %(full_task_name)s, %(ticks_to_skip)s ticks left until next run"
msgstr ""

#: nova/manager.py:172
#, python-format
msgid "Running periodic task %(full_task_name)s"
msgstr ""

#: nova/manager.py:182
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: nova/manager.py:255
msgid "Notifying Schedulers of capabilities ..."
msgstr ""

#: nova/notifications.py:112 nova/notifications.py:152
msgid "Failed to send state update notification"
msgstr ""

#: nova/policy.py:32
msgid "JSON file representing policy"
msgstr ""

#: nova/policy.py:35
msgid "Rule checked when requested rule is not found"
msgstr ""

#: nova/quota.py:726
#, python-format
msgid "Created reservations %(reservations)s"
msgstr ""

#: nova/quota.py:745
#, python-format
msgid "Failed to commit reservations %(reservations)s"
msgstr ""

#: nova/quota.py:763
#, python-format
msgid "Failed to roll back reservations %(reservations)s"
msgstr ""

#: nova/service.py:170
msgid "Full set of FLAGS:"
msgstr ""

#: nova/service.py:177
#, python-format
msgid "%(flag)s : FLAG SET "
msgstr ""

#: nova/service.py:187 nova/service.py:285
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: nova/service.py:231
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: nova/service.py:267
msgid "Forking too fast, sleeping"
msgstr ""

#: nova/service.py:290
msgid "Unhandled exception"
msgstr ""

#: nova/service.py:297
#, python-format
msgid "Started child %d"
msgstr ""

#: nova/service.py:307
#, python-format
msgid "Starting %d workers"
msgstr ""

#: nova/service.py:321
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: nova/service.py:324
#, python-format
msgid "Child %(pid)d exited with status %(code)d"
msgstr ""

#: nova/service.py:327
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: nova/service.py:347
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: nova/service.py:358
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: nova/service.py:387
#, python-format
msgid "Starting %(topic)s node (version %(vcs_string)s)"
msgstr ""

#: nova/service.py:403
#, python-format
msgid "Creating Consumer connection for Service %s"
msgstr ""

#: nova/service.py:495
msgid "Service killed that has no database entry"
msgstr ""

#: nova/service.py:532
msgid "The service database object disappeared, Recreating it."
msgstr ""

#: nova/service.py:547
msgid "Recovered model server connection!"
msgstr ""

#: nova/service.py:553
msgid "model server went away"
msgstr ""

#: nova/service.py:644
msgid "serve() can only be called once"
msgstr ""

#: nova/utils.py:170
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: nova/utils.py:181
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: nova/utils.py:197 nova/utils.py:275 nova/virt/powervm/common.py:82
#, python-format
msgid "Result was %s"
msgstr ""

#: nova/utils.py:210
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: nova/utils.py:250
#, python-format
msgid "Running cmd (SSH): %s"
msgstr ""

#: nova/utils.py:252
msgid "Environment not supported over SSH"
msgstr ""

#: nova/utils.py:256
msgid "process_input not supported over SSH"
msgstr ""

#: nova/utils.py:291
#, python-format
msgid "debug in callback: %s"
msgstr ""

#: nova/utils.py:450
#, python-format
msgid "Link Local address is not found.:%s"
msgstr ""

#: nova/utils.py:453
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr ""

#: nova/utils.py:488
#, python-format
msgid "Invalid backend: %s"
msgstr ""

#: nova/utils.py:549
msgid "in looping call"
msgstr ""

#: nova/utils.py:609
#, python-format
msgid "Unknown byte multiplier: %s"
msgstr ""

#: nova/utils.py:738
#, python-format
msgid "Expected object of type: %s"
msgstr ""

#: nova/utils.py:767
#, python-format
msgid "Invalid server_string: %s"
msgstr ""

#: nova/utils.py:907
#, python-format
msgid "timefunc: '%(name)s' took %(total_time).2f secs"
msgstr ""

#: nova/utils.py:985
#, python-format
msgid "Reloading cached file %s"
msgstr ""

#: nova/utils.py:1103 nova/virt/configdrive.py:151
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr ""

#: nova/wsgi.py:85
#, python-format
msgid "%(name)s listening on %(host)s:%(port)s"
msgstr ""

#: nova/wsgi.py:109
msgid "Stopping WSGI server."
msgstr ""

#: nova/wsgi.py:127
msgid "WSGI server has stopped."
msgstr ""

#: nova/wsgi.py:196
msgid "You must implement __call__"
msgstr ""

#: nova/wsgi.py:382
#, python-format
msgid "Loading app %(name)s from %(path)s"
msgstr ""

#: nova/api/auth.py:108
msgid "Invalid service catalog json."
msgstr ""

#: nova/api/auth.py:131
msgid "Sourcing roles from deprecated X-Role HTTP header"
msgstr ""

#: nova/api/sizelimit.py:51
msgid "Request is too large."
msgstr ""

#: nova/api/validator.py:138
#, python-format
msgid "%(key)s with value %(value)s failed validator %(name)s"
msgstr ""

#: nova/api/ec2/__init__.py:82
#, python-format
msgid "%(code)s: %(message)s"
msgstr ""

#: nova/api/ec2/__init__.py:105
#, python-format
msgid "FaultWrapper: %s"
msgstr ""

#: nova/api/ec2/__init__.py:180
msgid "Too many failed authentications."
msgstr ""

#: nova/api/ec2/__init__.py:190
#, python-format
msgid ""
"Access key %(access_key)s has had %(failures)d failed authentications and"
" will be locked out for %(lock_mins)d minutes."
msgstr ""

#: nova/api/ec2/__init__.py:207
msgid "Signature not provided"
msgstr ""

#: nova/api/ec2/__init__.py:211
msgid "Access key not provided"
msgstr ""

#: nova/api/ec2/__init__.py:246 nova/api/ec2/__init__.py:261
msgid "Failure communicating with keystone"
msgstr ""

#: nova/api/ec2/__init__.py:320
msgid "Timestamp failed validation."
msgstr ""

#: nova/api/ec2/__init__.py:340
#, python-format
msgid "action: %s"
msgstr ""

#: nova/api/ec2/__init__.py:342
#, python-format
msgid "arg: %(key)s\t\tval: %(value)s"
msgstr ""

#: nova/api/ec2/__init__.py:417
#, python-format
msgid "Unauthorized request for controller=%(controller)s and action=%(action)s"
msgstr ""

#: nova/api/ec2/__init__.py:489
#, python-format
msgid "InstanceNotFound raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:495
#, python-format
msgid "VolumeNotFound raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:501
#, python-format
msgid "SnapshotNotFound raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:507
#, python-format
msgid "NotFound raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:510
#, python-format
msgid "EC2APIError raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:518
#, python-format
msgid "KeyPairExists raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:522
#, python-format
msgid "InvalidParameterValue raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:526
#, python-format
msgid "InvalidPortRange raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:530
#, python-format
msgid "NotAuthorized raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:534
#, python-format
msgid "InvalidRequest raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:538
#, python-format
msgid "QuotaError raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:542
#, python-format
msgid "Invalid id: bogus (expecting \"i-...\"): %s"
msgstr ""

#: nova/api/ec2/__init__.py:551
#, python-format
msgid "Unexpected error raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:552
#, python-format
msgid "Environment: %s"
msgstr ""

#: nova/api/ec2/__init__.py:554 nova/api/metadata/handler.py:79
msgid "An unknown error has occurred. Please try your request again."
msgstr ""

#: nova/api/ec2/apirequest.py:64
#, python-format
msgid "Unsupported API request: controller = %(controller)s, action = %(action)s"
msgstr ""

#: nova/api/ec2/cloud.py:337
#, python-format
msgid "Create snapshot of volume %s"
msgstr ""

#: nova/api/ec2/cloud.py:363
#, python-format
msgid "Could not find key pair(s): %s"
msgstr ""

#: nova/api/ec2/cloud.py:379
#, python-format
msgid "Create key pair %s"
msgstr ""

#: nova/api/ec2/cloud.py:386 nova/api/ec2/cloud.py:411
#: nova/api/openstack/compute/contrib/keypairs.py:93
msgid "Quota exceeded, too many key pairs."
msgstr ""

#: nova/api/ec2/cloud.py:392 nova/api/ec2/cloud.py:417
#: nova/api/openstack/compute/contrib/keypairs.py:101
#, python-format
msgid "Key pair '%s' already exists."
msgstr ""

#: nova/api/ec2/cloud.py:401
#, python-format
msgid "Import key %s"
msgstr ""

#: nova/api/ec2/cloud.py:424
#, python-format
msgid "Delete key pair %s"
msgstr ""

#: nova/api/ec2/cloud.py:558 nova/api/ec2/cloud.py:679
msgid "Not enough parameters, need group_name or group_id"
msgstr ""

#: nova/api/ec2/cloud.py:563
#, python-format
msgid "%s Not enough parameters to build a valid rule"
msgstr ""

#: nova/api/ec2/cloud.py:601 nova/api/ec2/cloud.py:633
msgid "No rule for the specified parameters."
msgstr ""

#: nova/api/ec2/cloud.py:624
#, python-format
msgid "%s - This rule already exists in group"
msgstr ""

#: nova/api/ec2/cloud.py:690
#, python-format
msgid "Get console output for instance %s"
msgstr ""

#: nova/api/ec2/cloud.py:766
#, python-format
msgid "Create volume from snapshot %s"
msgstr ""

#: nova/api/ec2/cloud.py:770 nova/api/openstack/compute/contrib/volumes.py:243
#, python-format
msgid "Create volume of %s GB"
msgstr ""

#: nova/api/ec2/cloud.py:798
msgid "Delete Failed"
msgstr ""

#: nova/api/ec2/cloud.py:811
#, python-format
msgid "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"
msgstr ""

#: nova/api/ec2/cloud.py:819
msgid "Attach Failed."
msgstr ""

#: nova/api/ec2/cloud.py:832 nova/api/openstack/compute/contrib/volumes.py:422
#, python-format
msgid "Detach volume %s"
msgstr ""

#: nova/api/ec2/cloud.py:838
msgid "Detach Volume Failed."
msgstr ""

#: nova/api/ec2/cloud.py:864 nova/api/ec2/cloud.py:921
#: nova/api/ec2/cloud.py:1458 nova/api/ec2/cloud.py:1473
#, python-format
msgid "attribute not supported: %s"
msgstr ""

#: nova/api/ec2/cloud.py:987
#, python-format
msgid "vol = %s\n"
msgstr ""

#: nova/api/ec2/cloud.py:1138
msgid "Allocate address"
msgstr ""

#: nova/api/ec2/cloud.py:1142
msgid "No more floating IPs available"
msgstr ""

#: nova/api/ec2/cloud.py:1146
#, python-format
msgid "Release address %s"
msgstr ""

#: nova/api/ec2/cloud.py:1151
msgid "Unable to release IP Address."
msgstr ""

#: nova/api/ec2/cloud.py:1154
#, python-format
msgid "Associate address %(public_ip)s to instance %(instance_id)s"
msgstr ""

#: nova/api/ec2/cloud.py:1162
msgid "Unable to associate IP Address, no fixed_ips."
msgstr ""

#: nova/api/ec2/cloud.py:1170
#: nova/api/openstack/compute/contrib/floating_ips.py:257
#, python-format
msgid "multiple fixed_ips exist, using the first: %s"
msgstr ""

#: nova/api/ec2/cloud.py:1179
msgid "Floating ip is already associated."
msgstr ""

#: nova/api/ec2/cloud.py:1182
msgid "l3driver call to add floating ip failed."
msgstr ""

#: nova/api/ec2/cloud.py:1185
msgid "Error, unable to associate floating ip."
msgstr ""

#: nova/api/ec2/cloud.py:1193
#, python-format
msgid "Disassociate address %s"
msgstr ""

#: nova/api/ec2/cloud.py:1198
msgid "Floating ip is not associated."
msgstr ""

#: nova/api/ec2/cloud.py:1201
#: nova/api/openstack/compute/contrib/floating_ips.py:100
msgid "Cannot disassociate auto assigned floating ip"
msgstr ""

#: nova/api/ec2/cloud.py:1228
msgid "Image must be available"
msgstr ""

#: nova/api/ec2/cloud.py:1260
msgid "Going to start terminating instances"
msgstr ""

#: nova/api/ec2/cloud.py:1270
#, python-format
msgid "Reboot instance %r"
msgstr ""

#: nova/api/ec2/cloud.py:1279
msgid "Going to stop instances"
msgstr ""

#: nova/api/ec2/cloud.py:1288
msgid "Going to start instances"
msgstr ""

#: nova/api/ec2/cloud.py:1379
#, python-format
msgid "De-registering image %s"
msgstr ""

#: nova/api/ec2/cloud.py:1395
msgid "imageLocation is required"
msgstr ""

#: nova/api/ec2/cloud.py:1414
#, python-format
msgid "Registered image %(image_location)s with id %(image_id)s"
msgstr ""

#: nova/api/ec2/cloud.py:1476
msgid "user or group not specified"
msgstr ""

#: nova/api/ec2/cloud.py:1478
msgid "only group \"all\" is supported"
msgstr ""

#: nova/api/ec2/cloud.py:1480
msgid "operation_type must be add or remove"
msgstr ""

#: nova/api/ec2/cloud.py:1482
#, python-format
msgid "Updating image %s publicity"
msgstr ""

#: nova/api/ec2/cloud.py:1495
#, python-format
msgid "Not allowed to modify attributes for image %s"
msgstr ""

#: nova/api/ec2/cloud.py:1524
#, python-format
msgid ""
"Invalid value '%(ec2_instance_id)s' for instanceId. Instance does not "
"have a volume attached at root (%(root)s)"
msgstr ""

#: nova/api/ec2/cloud.py:1554
#, python-format
msgid "Couldn't stop instance with in %d sec"
msgstr ""

#: nova/api/ec2/cloud.py:1572
#, python-format
msgid "image of %(instance)s at %(now)s"
msgstr ""

#: nova/api/ec2/cloud.py:1605
msgid "Invalid CIDR"
msgstr ""

#: nova/api/ec2/ec2utils.py:189
msgid "Request must include either Timestamp or Expires, but cannot contain both"
msgstr ""

#: nova/api/ec2/ec2utils.py:209
msgid "Timestamp is invalid."
msgstr ""

#: nova/api/metadata/handler.py:77 nova/api/metadata/handler.py:84
#, python-format
msgid "Failed to get metadata for ip: %s"
msgstr ""

#: nova/api/openstack/__init__.py:51
#, python-format
msgid "Caught error: %s"
msgstr ""

#: nova/api/openstack/__init__.py:60 nova/api/openstack/wsgi.py:986
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr ""

#: nova/api/openstack/__init__.py:126
msgid "Must specify an ExtensionManager class"
msgstr ""

#: nova/api/openstack/__init__.py:137
#, python-format
msgid "Extended resource: %s"
msgstr ""

#: nova/api/openstack/__init__.py:171
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: nova/api/openstack/__init__.py:176
#, python-format
msgid "Extension %(ext_name)s extending resource: %(collection)s"
msgstr ""

#: nova/api/openstack/common.py:99
#, python-format
msgid ""
"status is UNKNOWN from vm_state=%(vm_state)s task_state=%(task_state)s. "
"Bad upgrade or db corrupted?"
msgstr ""

#: nova/api/openstack/common.py:138 nova/api/openstack/common.py:172
msgid "limit param must be an integer"
msgstr ""

#: nova/api/openstack/common.py:141 nova/api/openstack/common.py:176
msgid "limit param must be positive"
msgstr ""

#: nova/api/openstack/common.py:166
msgid "offset param must be an integer"
msgstr ""

#: nova/api/openstack/common.py:180
msgid "offset param must be positive"
msgstr ""

#: nova/api/openstack/common.py:215 nova/api/openstack/compute/servers.py:536
#, python-format
msgid "marker [%s] not found"
msgstr ""

#: nova/api/openstack/common.py:255
#, python-format
msgid "href %s does not contain version"
msgstr ""

#: nova/api/openstack/common.py:270
msgid "Image metadata limit exceeded"
msgstr ""

#: nova/api/openstack/common.py:278
msgid "Image metadata key cannot be blank"
msgstr ""

#: nova/api/openstack/common.py:281
msgid "Image metadata key too long"
msgstr ""

#: nova/api/openstack/common.py:284
msgid "Invalid image metadata"
msgstr ""

#: nova/api/openstack/common.py:335
#, python-format
msgid "Cannot '%(action)s' while instance is in %(attr)s %(state)s"
msgstr ""

#: nova/api/openstack/common.py:338
#, python-format
msgid "Instance is in an invalid state for '%(action)s'"
msgstr ""

#: nova/api/openstack/common.py:418
msgid "Rejecting snapshot request, snapshots currently disabled"
msgstr ""

#: nova/api/openstack/common.py:420
msgid "Instance snapshots are not permitted at this time."
msgstr ""

#: nova/api/openstack/extensions.py:198
#, python-format
msgid "Loaded extension: %s"
msgstr ""

#: nova/api/openstack/extensions.py:237
#, python-format
msgid "Ext name: %s"
msgstr ""

#: nova/api/openstack/extensions.py:238
#, python-format
msgid "Ext alias: %s"
msgstr ""

#: nova/api/openstack/extensions.py:239
#, python-format
msgid "Ext description: %s"
msgstr ""

#: nova/api/openstack/extensions.py:241
#, python-format
msgid "Ext namespace: %s"
msgstr ""

#: nova/api/openstack/extensions.py:242
#, python-format
msgid "Ext updated: %s"
msgstr ""

#: nova/api/openstack/extensions.py:244
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: nova/api/openstack/extensions.py:258
#, python-format
msgid "Loading extension %s"
msgstr ""

#: nova/api/openstack/extensions.py:267
#, python-format
msgid "Calling extension factory %s"
msgstr ""

#: nova/api/openstack/extensions.py:279
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: nova/api/openstack/extensions.py:360
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr ""

#: nova/api/openstack/extensions.py:384
#, python-format
msgid "Failed to load extension %(ext_name)s: %(exc)s"
msgstr ""

#: nova/api/openstack/wsgi.py:199 nova/api/openstack/wsgi.py:619
msgid "cannot understand JSON"
msgstr ""

#: nova/api/openstack/wsgi.py:223
#: nova/api/openstack/compute/contrib/hosts.py:85
msgid "cannot understand XML"
msgstr ""

#: nova/api/openstack/wsgi.py:624
msgid "too many body keys"
msgstr ""

#: nova/api/openstack/wsgi.py:667
#, python-format
msgid "Exception handling resource: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:671
#, python-format
msgid "Fault thrown: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:674
#, python-format
msgid "HTTP exception thrown: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:788
msgid "Unrecognized Content-Type provided in request"
msgstr ""

#: nova/api/openstack/wsgi.py:792
msgid "No Content-Type provided in request"
msgstr ""

#: nova/api/openstack/wsgi.py:796
msgid "Empty body provided in request"
msgstr ""

#: nova/api/openstack/wsgi.py:897
msgid "Invalid XML in request body"
msgstr ""

#: nova/api/openstack/wsgi.py:916
#, python-format
msgid "There is no such action: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:919 nova/api/openstack/wsgi.py:932
#: nova/api/openstack/compute/server_metadata.py:58
#: nova/api/openstack/compute/server_metadata.py:76
#: nova/api/openstack/compute/server_metadata.py:101
#: nova/api/openstack/compute/server_metadata.py:126
#: nova/api/openstack/compute/contrib/admin_actions.py:215
msgid "Malformed request body"
msgstr ""

#: nova/api/openstack/wsgi.py:929
msgid "Unsupported Content-Type"
msgstr ""

#: nova/api/openstack/wsgi.py:941
msgid "Malformed request url"
msgstr ""

#: nova/api/openstack/wsgi.py:989
#, python-format
msgid "%(url)s returned a fault: %(e)s"
msgstr ""

#: nova/api/openstack/xmlutil.py:265
msgid "element is not a child"
msgstr ""

#: nova/api/openstack/xmlutil.py:414
msgid "root element selecting a list"
msgstr ""

#: nova/api/openstack/xmlutil.py:739
#, python-format
msgid "Template tree mismatch; adding slave %(slavetag)s to master %(mastertag)s"
msgstr ""

#: nova/api/openstack/xmlutil.py:858
msgid "subclasses must implement construct()!"
msgstr ""

#: nova/api/openstack/compute/extensions.py:30
msgid "Initializing extension manager."
msgstr ""

#: nova/api/openstack/compute/flavors.py:111
#, python-format
msgid "Invalid is_public filter [%s]"
msgstr ""

#: nova/api/openstack/compute/flavors.py:130
#, python-format
msgid "Invalid minRam filter [%s]"
msgstr ""

#: nova/api/openstack/compute/flavors.py:137
#, python-format
msgid "Invalid minDisk filter [%s]"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:40
#: nova/api/openstack/compute/images.py:146
#: nova/api/openstack/compute/images.py:161
msgid "Image not found."
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:80
msgid "Incorrect request body format"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:84
#: nova/api/openstack/compute/server_metadata.py:80
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:79
msgid "Request body and URI mismatch"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:87
#: nova/api/openstack/compute/server_metadata.py:84
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:82
msgid "Request body contains too many items"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:113
msgid "Invalid metadata key"
msgstr ""

#: nova/api/openstack/compute/ips.py:74
msgid "Instance does not exist"
msgstr ""

#: nova/api/openstack/compute/ips.py:97
msgid "Instance is not a member of specified network"
msgstr ""

#: nova/api/openstack/compute/limits.py:145
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: nova/api/openstack/compute/limits.py:271
msgid "This request was rate-limited."
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:38
#: nova/api/openstack/compute/server_metadata.py:122
#: nova/api/openstack/compute/server_metadata.py:166
msgid "Server does not exist"
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:148
#: nova/api/openstack/compute/server_metadata.py:159
msgid "Metadata item was not found"
msgstr ""

#: nova/api/openstack/compute/servers.py:445
#: nova/api/openstack/compute/servers.py:457
#: nova/api/openstack/compute/servers.py:552
#: nova/api/openstack/compute/servers.py:720
#: nova/api/openstack/compute/servers.py:981
#: nova/api/openstack/compute/servers.py:1084
#: nova/api/openstack/compute/servers.py:1234
msgid "Instance could not be found"
msgstr ""

#: nova/api/openstack/compute/servers.py:496
msgid "Invalid changes-since value"
msgstr ""

#: nova/api/openstack/compute/servers.py:515
msgid "Only administrators may list deleted instances"
msgstr ""

#: nova/api/openstack/compute/servers.py:559
msgid "Server name is not a string or unicode"
msgstr ""

#: nova/api/openstack/compute/servers.py:563
msgid "Server name is an empty string"
msgstr ""

#: nova/api/openstack/compute/servers.py:567
msgid "Server name must be less than 256 characters."
msgstr ""

#: nova/api/openstack/compute/servers.py:584
#, python-format
msgid "Bad personality format: missing %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:587
msgid "Bad personality format"
msgstr ""

#: nova/api/openstack/compute/servers.py:591
#, python-format
msgid "Personality content for %s cannot be decoded"
msgstr ""

#: nova/api/openstack/compute/servers.py:622
msgid "Unknown argment : port"
msgstr ""

#: nova/api/openstack/compute/servers.py:625
#, python-format
msgid "Bad port format: port uuid is not in proper format (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:635
#, python-format
msgid "Bad networks format: network uuid is not in proper format (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:645
#, python-format
msgid "Invalid fixed IP address (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:658
#, python-format
msgid "Duplicate networks (%s) are not allowed"
msgstr ""

#: nova/api/openstack/compute/servers.py:664
#, python-format
msgid "Bad network format: missing %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:667
msgid "Bad networks format"
msgstr ""

#: nova/api/openstack/compute/servers.py:693
msgid "Userdata content cannot be decoded"
msgstr ""

#: nova/api/openstack/compute/servers.py:700
msgid "accessIPv4 is not proper IPv4 format"
msgstr ""

#: nova/api/openstack/compute/servers.py:707
msgid "accessIPv6 is not proper IPv6 format"
msgstr ""

#: nova/api/openstack/compute/servers.py:736
msgid "Server name is not defined"
msgstr ""

#: nova/api/openstack/compute/servers.py:785
#: nova/api/openstack/compute/servers.py:891
msgid "Invalid flavorRef provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:825
msgid "min_count must be an integer value"
msgstr ""

#: nova/api/openstack/compute/servers.py:828
msgid "min_count must be > 0"
msgstr ""

#: nova/api/openstack/compute/servers.py:833
msgid "max_count must be an integer value"
msgstr ""

#: nova/api/openstack/compute/servers.py:836
msgid "max_count must be > 0"
msgstr ""

#: nova/api/openstack/compute/servers.py:839
msgid "min_count must be <= max_count"
msgstr ""

#: nova/api/openstack/compute/servers.py:888
msgid "Can not find requested image"
msgstr ""

#: nova/api/openstack/compute/servers.py:894
msgid "Invalid key_name provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:973
msgid "HostId cannot be updated."
msgstr ""

#: nova/api/openstack/compute/servers.py:999
#: nova/api/openstack/compute/servers.py:1019
msgid "Instance has not been resized."
msgstr ""

#: nova/api/openstack/compute/servers.py:1005
#, python-format
msgid "Error in confirm-resize %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:1025
#, python-format
msgid "Error in revert-resize %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:1038
msgid "Argument 'type' for reboot is not HARD or SOFT"
msgstr ""

#: nova/api/openstack/compute/servers.py:1042
msgid "Missing argument 'type' for reboot"
msgstr ""

#: nova/api/openstack/compute/servers.py:1055
#, python-format
msgid "Error in reboot %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:1067
msgid "Unable to locate requested flavor."
msgstr ""

#: nova/api/openstack/compute/servers.py:1070
msgid "Resize requires a flavor change."
msgstr ""

#: nova/api/openstack/compute/servers.py:1094
msgid "Missing imageRef attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:1103
msgid "Invalid imageRef provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:1112
msgid "Missing flavorRef attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:1125
msgid "No adminPass was specified"
msgstr ""

#: nova/api/openstack/compute/servers.py:1129
#: nova/api/openstack/compute/servers.py:1331
msgid "Invalid adminPass"
msgstr ""

#: nova/api/openstack/compute/servers.py:1140
msgid "Unable to parse metadata key/value pairs."
msgstr ""

#: nova/api/openstack/compute/servers.py:1153
msgid "Resize request has invalid 'flavorRef' attribute."
msgstr ""

#: nova/api/openstack/compute/servers.py:1156
msgid "Resize requests require 'flavorRef' attribute."
msgstr ""

#: nova/api/openstack/compute/servers.py:1174
#: nova/api/openstack/compute/contrib/aggregates.py:142
#: nova/api/openstack/compute/contrib/keypairs.py:78
#: nova/api/openstack/compute/contrib/networks.py:75
msgid "Invalid request body"
msgstr ""

#: nova/api/openstack/compute/servers.py:1179
msgid "Could not parse imageRef from request."
msgstr ""

#: nova/api/openstack/compute/servers.py:1241
msgid "Cannot find image for rebuild"
msgstr ""

#: nova/api/openstack/compute/servers.py:1274
msgid "createImage entity requires name attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:1358
#, python-format
msgid "Removing options '%(unk_opt_str)s' from query"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:64
#, python-format
msgid "Compute.api::pause %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:81
#, python-format
msgid "Compute.api::unpause %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:98
#, python-format
msgid "compute.api::suspend %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:115
#, python-format
msgid "compute.api::resume %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:131
#, python-format
msgid "Error in migrate %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:145
#, python-format
msgid "Compute.api::reset_network %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:158
#: nova/api/openstack/compute/contrib/admin_actions.py:174
#: nova/api/openstack/compute/contrib/admin_actions.py:190
#: nova/api/openstack/compute/contrib/admin_actions.py:312
#: nova/api/openstack/compute/contrib/multinic.py:41
#: nova/api/openstack/compute/contrib/rescue.py:44
msgid "Server not found"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:161
#, python-format
msgid "Compute.api::inject_network_info %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:177
#, python-format
msgid "Compute.api::lock %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:193
#, python-format
msgid "Compute.api::unlock %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:223
#, python-format
msgid "createBackup entity requires %s attribute"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:227
msgid "Malformed createBackup entity"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:233
msgid "createBackup attribute 'rotation' must be an integer"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:248
#: nova/api/openstack/compute/contrib/console_output.py:47
#: nova/api/openstack/compute/contrib/server_diagnostics.py:47
#: nova/api/openstack/compute/contrib/server_start_stop.py:38
msgid "Instance not found"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:276
msgid "host and block_migration must be specified."
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:284
#, python-format
msgid "Live migration of instance %(id)s to host %(host)s failed"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:302
#, python-format
msgid "Desired state must be specified.  Valid states are: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:315
#, python-format
msgid "Compute.api::resetState %s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:76
#, python-format
msgid ""
"Cannot create aggregate with name %(name)s and availability zone "
"%(avail_zone)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:88
#, python-format
msgid "Cannot show aggregate: %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:114
#, python-format
msgid "Cannot update aggregate: %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:126
#, python-format
msgid "Cannot delete aggregate: %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:139
#, python-format
msgid "Aggregates does not have %s action"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:152
#: nova/api/openstack/compute/contrib/aggregates.py:157
#, python-format
msgid "Cannot add host %(host)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:170
#: nova/api/openstack/compute/contrib/aggregates.py:174
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:194
#, python-format
msgid "Cannot set metadata %(metadata)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/certificates.py:76
msgid "Only root certificate can be retrieved."
msgstr ""

#: nova/api/openstack/compute/contrib/cloudpipe.py:149
msgid ""
"Unable to claim IP for VPN instances, ensure it isn't running, and try "
"again in a few minutes"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:52
msgid "os-getConsoleOutput malformed or missing from request body"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:59
msgid "Length in request body must be an integer value"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:67
msgid "Unable to get console"
msgstr ""

#: nova/api/openstack/compute/contrib/disk_config.py:43
#, python-format
msgid "%s must be either 'MANUAL' or 'AUTO'."
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:80
#: nova/api/openstack/compute/contrib/flavor_access.py:104
msgid "Flavor not found."
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:109
msgid "Access list not available for public flavors."
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:121
msgid "No request body"
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:49
msgid "No Request Body"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:97
msgid "Floating ip is not associated"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:151
#: nova/api/openstack/compute/contrib/floating_ips.py:199
#, python-format
msgid "Floating ip not found for id %s"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:184
#, python-format
msgid "No more floating ips in pool %s."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:186
msgid "No more floating ips available."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:234
#: nova/api/openstack/compute/contrib/floating_ips.py:290
#: nova/api/openstack/compute/contrib/security_groups.py:417
msgid "Missing parameter dict"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:237
#: nova/api/openstack/compute/contrib/floating_ips.py:293
msgid "Address not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:244
msgid "No nw_info cache associated with instance"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:249
msgid "No fixed ips associated to instance"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:265
msgid "floating ip is already associated"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:268
msgid "l3driver call to add floating ip failed"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:272
#: nova/api/openstack/compute/contrib/floating_ips.py:301
msgid "floating ip not found"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:275
msgid "Error. Unable to associate floating ip"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:124
#, python-format
msgid "Host '%s' could not be found."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:153
#, python-format
msgid "Invalid status: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:157
#, python-format
msgid "Invalid mode: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:161
#, python-format
msgid "Invalid update setting: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:179
#, python-format
msgid "Putting host %(host)s in maintenance mode %(mode)s."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:190
#, python-format
msgid "Setting host %(host)s to %(state)s."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:237
msgid "Describe-resource is admin only functionality"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:245
msgid "Host not found"
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:184
#: nova/api/openstack/compute/contrib/hypervisors.py:195
#, python-format
msgid "Hypervisor with ID '%s' could not be found."
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:203
msgid "Virt driver does not implement uptime function."
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:218
#: nova/api/openstack/compute/contrib/hypervisors.py:232
#, python-format
msgid "No hypervisor matching '%s' could be found."
msgstr ""

#: nova/api/openstack/compute/contrib/instance_usage_audit_log.py:54
#, python-format
msgid "Invalid timestamp for date %s"
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:52
msgid "Missing 'networkId' argument for addFixedIp"
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:68
msgid "Missing 'address' argument for removeFixedIp"
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:77
#, python-format
msgid "Unable to find address %r"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:72
#, python-format
msgid "Network does not have %s action"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:80
#, python-format
msgid "Disassociating network with id %s"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:84
#: nova/api/openstack/compute/contrib/networks.py:101
#: nova/api/openstack/compute/contrib/networks.py:111
msgid "Network not found"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:97
#, python-format
msgid "Showing network with id %s"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:107
#, python-format
msgid "Deleting network with id %s"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:122
msgid "Missing network in body"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:126
msgid "Network label is required"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:130
msgid "Network cidr or cidr_v6 is required"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:132
#, python-format
msgid "Creating network with label %s"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:148
#, python-format
msgid "Associating network %(network)s with project %(project)s"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:156
#, python-format
msgid "Cannot associate network %(network)s with project %(project)s: %(message)s"
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:63
msgid "Quota limit must be -1 or greater."
msgstr ""

#: nova/api/openstack/compute/contrib/scheduler_hints.py:41
msgid "Malformed scheduler_hints attribute"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:224
msgid "Security group id should be integer"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:333
msgid "Not enough parameters to build a valid rule."
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:339
#, python-format
msgid "This rule already exists in group %s"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:420
msgid "Security group not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:424
msgid "Security group name cannot be empty"
msgstr ""

#: nova/api/openstack/compute/contrib/server_start_stop.py:46
msgid "start instance"
msgstr ""

#: nova/api/openstack/compute/contrib/server_start_stop.py:55
msgid "stop instance"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:75
#, python-format
msgid "vol=%s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:187
#, python-format
msgid "Delete volume with id: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:352
#: nova/api/openstack/compute/contrib/volumes.py:432
#, python-format
msgid "Instance %s is not attached."
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:383
#, python-format
msgid "Attach volume %(volume_id)s to instance %(server_id)s at %(device)s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:546
#, python-format
msgid "Delete snapshot with id: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:589
#, python-format
msgid "Create snapshot from volume %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:593
#, python-format
msgid "Invalid value '%s' for force. "
msgstr ""

#: nova/api/openstack/compute/views/servers.py:182
msgid "Instance has had its instance_type removed from the DB"
msgstr ""

#: nova/cloudpipe/pipelib.py:44
msgid "Instance type for vpn instances"
msgstr ""

#: nova/cloudpipe/pipelib.py:47
msgid "Template for cloudpipe instance boot script"
msgstr ""

#: nova/cloudpipe/pipelib.py:50
msgid "Network to push into openvpn config"
msgstr ""

#: nova/cloudpipe/pipelib.py:53
msgid "Netmask to push into openvpn config"
msgstr ""

#: nova/cloudpipe/pipelib.py:106
#, python-format
msgid "Launching VPN for %s"
msgstr ""

#: nova/common/sqlalchemyutils.py:68
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: nova/common/sqlalchemyutils.py:116
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: nova/compute/api.py:221
msgid "Cannot run any more instances of this type."
msgstr ""

#: nova/compute/api.py:228
#, python-format
msgid "Can only run %s more instances of this type."
msgstr ""

#: nova/compute/api.py:237
#, python-format
msgid ""
"%(overs)s quota exceeded for %(pid)s, tried to run %(min_count)s "
"instances. %(msg)s"
msgstr ""

#: nova/compute/api.py:257
#, python-format
msgid ""
"Quota exceeded for %(pid)s, tried to set %(num_metadata)s metadata "
"properties"
msgstr ""

#: nova/compute/api.py:267
msgid "Metadata property key blank"
msgstr ""

#: nova/compute/api.py:271
msgid "Metadata property key greater than 255 characters"
msgstr ""

#: nova/compute/api.py:275
msgid "Metadata property value greater than 255 characters"
msgstr ""

#: nova/compute/api.py:499
#, python-format
msgid "Going to run %s instances..."
msgstr ""

#: nova/compute/api.py:570
#, python-format
msgid "bdm %s"
msgstr ""

#: nova/compute/api.py:597
#, python-format
msgid "block_device_mapping %s"
msgstr ""

#: nova/compute/api.py:829
msgid "Going to try to soft delete instance"
msgstr ""

#: nova/compute/api.py:846
msgid "No host for instance, deleting immediately"
msgstr ""

#: nova/compute/api.py:946
msgid "host for instance is down, deleting from database"
msgstr ""

#: nova/compute/api.py:990
msgid "Going to try to terminate instance"
msgstr ""

#: nova/compute/api.py:1030
msgid "Going to try to stop instance"
msgstr ""

#: nova/compute/api.py:1044
msgid "Going to try to start instance"
msgstr ""

#: nova/compute/api.py:1108
#, python-format
msgid "Searching by: %s"
msgstr ""

#: nova/compute/api.py:1243
#, python-format
msgid "Image type not recognized %s"
msgstr ""

#: nova/compute/api.py:1352
#, python-format
msgid "snapshot for %s"
msgstr ""

#: nova/compute/api.py:1674
msgid "flavor_id is None. Assuming migration."
msgstr ""

#: nova/compute/api.py:1683
#, python-format
msgid ""
"Old instance type %(current_instance_type_name)s,  new instance type "
"%(new_instance_type_name)s"
msgstr ""

#: nova/compute/api.py:1725
#, python-format
msgid "%(overs)s quota exceeded for %(pid)s, tried to resize instance. %(msg)s"
msgstr ""

#: nova/compute/api.py:1897
msgid "Locking"
msgstr ""

#: nova/compute/api.py:1905
msgid "Unlocking"
msgstr ""

#: nova/compute/api.py:1973
msgid "Volume must be attached in order to detach."
msgstr ""

#: nova/compute/api.py:2058
#, python-format
msgid "Going to try to live migrate instance to %s"
msgstr ""

#: nova/compute/api.py:2207
msgid "Keypair name contains unsafe characters"
msgstr ""

#: nova/compute/api.py:2211
msgid "Keypair name must be between 1 and 255 characters long"
msgstr ""

#: nova/compute/api.py:2312
#, python-format
msgid "Security group %s is not a string or unicode"
msgstr ""

#: nova/compute/api.py:2315
#, python-format
msgid "Security group %s cannot be empty."
msgstr ""

#: nova/compute/api.py:2323
#, python-format
msgid ""
"Value (%(value)s) for parameter Group%(property)s is invalid. Content "
"limited to '%(allowed)'."
msgstr ""

#: nova/compute/api.py:2329
#, python-format
msgid "Security group %s should not be greater than 255 characters."
msgstr ""

#: nova/compute/api.py:2349
msgid "Quota exceeded, too many security groups."
msgstr ""

#: nova/compute/api.py:2352
#, python-format
msgid "Create Security Group %s"
msgstr ""

#: nova/compute/api.py:2359
#, python-format
msgid "Security group %s already exists"
msgstr ""

#: nova/compute/api.py:2424
msgid "Security group is still in use"
msgstr ""

#: nova/compute/api.py:2432
msgid "Failed to update usages deallocating security group"
msgstr ""

#: nova/compute/api.py:2435
#, python-format
msgid "Delete security group %s"
msgstr ""

#: nova/compute/api.py:2692
#, python-format
msgid "Rule (%s) not found"
msgstr ""

#: nova/compute/api.py:2701
msgid "Quota exceeded, too many security group rules."
msgstr ""

#: nova/compute/api.py:2704
#, python-format
msgid "Authorize security group ingress %s"
msgstr ""

#: nova/compute/api.py:2715
#, python-format
msgid "Revoke security group ingress %s"
msgstr ""

#: nova/compute/instance_types.py:63
msgid "names can only contain [a-zA-Z0-9_.- ]"
msgstr ""

#: nova/compute/instance_types.py:72 nova/compute/instance_types.py:80
msgid "create arguments must be positive integers"
msgstr ""

#: nova/compute/instance_types.py:94
#, python-format
msgid "DB error: %s"
msgstr ""

#: nova/compute/instance_types.py:104
#, python-format
msgid "Instance type %s not found for deletion"
msgstr ""

#: nova/compute/manager.py:163
msgid "Possibly task preempted."
msgstr ""

#: nova/compute/manager.py:243
msgid "Compute driver option required, but not specified"
msgstr ""

#: nova/compute/manager.py:248
#, python-format
msgid "Loading compute driver '%s'"
msgstr ""

#: nova/compute/manager.py:255
#, python-format
msgid "Unable to load the virtualization driver: %s"
msgstr ""

#: nova/compute/manager.py:290
msgid "Instance has been destroyed from under us while trying to set it to ERROR"
msgstr ""

#: nova/compute/manager.py:318
#, python-format
msgid "Current state is %(drv_state)s, state in DB is %(db_state)s."
msgstr ""

#: nova/compute/manager.py:332
msgid "Rebooting instance after nova-compute restart."
msgstr ""

#: nova/compute/manager.py:346
msgid "Hypervisor driver does not support resume guests"
msgstr ""

#: nova/compute/manager.py:356
msgid "Hypervisor driver does not support firewall rules"
msgstr ""

#: nova/compute/manager.py:375
msgid "Checking state"
msgstr ""

#: nova/compute/manager.py:448
#, python-format
msgid "Setting up bdm %s"
msgstr ""

#: nova/compute/manager.py:541
msgid "Failed to dealloc network for deleted instance"
msgstr ""

#: nova/compute/manager.py:564
#, python-format
msgid "Error: %s"
msgstr ""

#: nova/compute/manager.py:597 nova/compute/manager.py:1740
msgid "Error trying to reschedule"
msgstr ""

#: nova/compute/manager.py:614
msgid "Retry info not present, will not reschedule"
msgstr ""

#: nova/compute/manager.py:619
msgid "No request spec, will not reschedule"
msgstr ""

#: nova/compute/manager.py:625
#, python-format
msgid "Re-scheduling %(method)s: attempt %(num)d"
msgstr ""

#: nova/compute/manager.py:648
msgid "Instance build timed out. Set to error state."
msgstr ""

#: nova/compute/manager.py:679
msgid "Instance has already been created"
msgstr ""

#: nova/compute/manager.py:722
#, python-format
msgid ""
"image_id=%(image_id)s, image_size_bytes=%(size_bytes)d, "
"allowed_size_bytes=%(allowed_size_bytes)d"
msgstr ""

#: nova/compute/manager.py:728
#, python-format
msgid ""
"Image '%(image_id)s' size %(size_bytes)d exceeded instance_type allowed "
"size %(allowed_size_bytes)d"
msgstr ""

#: nova/compute/manager.py:738
msgid "Starting instance..."
msgstr ""

#: nova/compute/manager.py:759
msgid "Instance failed network setup"
msgstr ""

#: nova/compute/manager.py:763
#, python-format
msgid "Instance network_info: |%s|"
msgstr ""

#: nova/compute/manager.py:776
msgid "Instance failed block device setup"
msgstr ""

#: nova/compute/manager.py:794
msgid "Instance failed to spawn"
msgstr ""

#: nova/compute/manager.py:818
msgid "Deallocating network for instance"
msgstr ""

#: nova/compute/manager.py:890
#, python-format
msgid "%(action_str)s instance"
msgstr ""

#: nova/compute/manager.py:921
#, python-format
msgid "Ignoring DiskNotFound: %s"
msgstr ""

#: nova/compute/manager.py:924
#, python-format
msgid "Ignoring VolumeNotFound: %s"
msgstr ""

#: nova/compute/manager.py:931
#, python-format
msgid "terminating bdm %s"
msgstr ""

#: nova/compute/manager.py:955
#, python-format
msgid "Ignoring volume cleanup failure due to %s"
msgstr ""

#: nova/compute/manager.py:995 nova/compute/manager.py:1909
#: nova/compute/manager.py:3106
#, python-format
msgid "%s. Setting instance vm_state to ERROR"
msgstr ""

#: nova/compute/manager.py:1128
msgid "Rebuilding instance"
msgstr ""

#: nova/compute/manager.py:1207
msgid "Rebooting instance"
msgstr ""

#: nova/compute/manager.py:1231
#, python-format
msgid ""
"trying to reboot a non-running instance: (state: %(state)s expected: "
"%(running)s)"
msgstr ""

#: nova/compute/manager.py:1240
#, python-format
msgid "Cannot reboot instance: %(exc)s"
msgstr ""

#: nova/compute/manager.py:1277
msgid "instance snapshotting"
msgstr ""

#: nova/compute/manager.py:1283
#, python-format
msgid ""
"trying to snapshot a non-running instance: (state: %(state)s expected: "
"%(running)s)"
msgstr ""

#: nova/compute/manager.py:1336
#, python-format
msgid "Found %(num_images)d images (rotation: %(rotation)d)"
msgstr ""

#: nova/compute/manager.py:1343
#, python-format
msgid "Rotating out %d backups"
msgstr ""

#: nova/compute/manager.py:1348
#, python-format
msgid "Deleting image %s"
msgstr ""

#: nova/compute/manager.py:1379
#, python-format
msgid "Failed to set admin password. Instance %s is not running"
msgstr ""

#: nova/compute/manager.py:1386
msgid "Root password set"
msgstr ""

#: nova/compute/manager.py:1396
msgid "set_admin_password is not implemented by this driver."
msgstr ""

#: nova/compute/manager.py:1412
#, python-format
msgid "set_admin_password failed: %s"
msgstr ""

#: nova/compute/manager.py:1420
msgid "error setting admin password"
msgstr ""

#: nova/compute/manager.py:1435
#, python-format
msgid ""
"trying to inject a file into a non-running (state: "
"%(current_power_state)s expected: %(expected_state)s)"
msgstr ""

#: nova/compute/manager.py:1439
#, python-format
msgid "injecting file to %(path)s"
msgstr ""

#: nova/compute/manager.py:1452
msgid "Rescuing"
msgstr ""

#: nova/compute/manager.py:1479
msgid "Unrescuing"
msgstr ""

#: nova/compute/manager.py:1500
#, python-format
msgid "Changing instance metadata according to %(diff)r"
msgstr ""

#: nova/compute/manager.py:1677
msgid "destination same as source!"
msgstr ""

#: nova/compute/manager.py:1696
msgid "Migrating"
msgstr ""

#: nova/compute/manager.py:1906
#, python-format
msgid "Failed to rollback quota for failed finish_resize: %(qr_error)s"
msgstr ""

#: nova/compute/manager.py:1962
msgid "Pausing"
msgstr ""

#: nova/compute/manager.py:1979
msgid "Unpausing"
msgstr ""

#: nova/compute/manager.py:2017
msgid "Retrieving diagnostics"
msgstr ""

#: nova/compute/manager.py:2047
msgid "Resuming"
msgstr ""

#: nova/compute/manager.py:2063
msgid "Reset network"
msgstr ""

#: nova/compute/manager.py:2068
msgid "Inject network info"
msgstr ""

#: nova/compute/manager.py:2071
#, python-format
msgid "network_info to inject: |%s|"
msgstr ""

#: nova/compute/manager.py:2088
msgid "Get console output"
msgstr ""

#: nova/compute/manager.py:2113
msgid "Getting vnc console"
msgstr ""

#: nova/compute/manager.py:2141
#, python-format
msgid "Booting with volume %(volume_id)s at %(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:2185
#, python-format
msgid "Attaching volume %(volume_id)s to %(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:2194
#, python-format
msgid ""
"Failed to connect to volume %(volume_id)s while attaching at "
"%(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:2209
#, python-format
msgid "Failed to attach volume %(volume_id)s at %(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:2238
#, python-format
msgid "Detach volume %(volume_id)s from mountpoint %(mp)s"
msgstr ""

#: nova/compute/manager.py:2242
msgid "Detaching volume from unknown instance"
msgstr ""

#: nova/compute/manager.py:2255
#, python-format
msgid "Faild to detach volume %(volume_id)s from %(mp)s"
msgstr ""

#: nova/compute/manager.py:2299
#, python-format
msgid "Host %(host)s not found"
msgstr ""

#: nova/compute/manager.py:2359
msgid "Instance has no volume."
msgstr ""

#: nova/compute/manager.py:2419
#, python-format
msgid "Pre live migration failed at  %(dest)s"
msgstr ""

#: nova/compute/manager.py:2445
msgid "_post_live_migration() is started.."
msgstr ""

#: nova/compute/manager.py:2478
msgid "No floating_ip found"
msgstr ""

#: nova/compute/manager.py:2486
msgid "No floating_ip found."
msgstr ""

#: nova/compute/manager.py:2488
#, python-format
msgid ""
"Live migration: Unexpected error: cannot inherit floating ip.\n"
"%(e)s"
msgstr ""

#: nova/compute/manager.py:2514
#, python-format
msgid "Migrating instance to %(dest)s finished successfully."
msgstr ""

#: nova/compute/manager.py:2516
msgid ""
"You may see the error \"libvirt: QEMU error: Domain not found: no domain "
"with matching name.\" This error can be safely ignored."
msgstr ""

#: nova/compute/manager.py:2530
msgid "Post operation of migration started"
msgstr ""

#: nova/compute/manager.py:2661
msgid "Updated the info_cache for instance"
msgstr ""

#: nova/compute/manager.py:2687
#, python-format
msgid ""
"Found %(migration_count)d unconfirmed migrations older than "
"%(confirm_window)d seconds"
msgstr ""

#: nova/compute/manager.py:2692
#, python-format
msgid "Setting migration %(migration_id)s to error: %(reason)s"
msgstr ""

#: nova/compute/manager.py:2701
#, python-format
msgid ""
"Automatically confirming migration %(migration_id)s for instance "
"%(instance_uuid)s"
msgstr ""

#: nova/compute/manager.py:2708
#, python-format
msgid "Instance %(instance_uuid)s not found"
msgstr ""

#: nova/compute/manager.py:2712
msgid "In ERROR state"
msgstr ""

#: nova/compute/manager.py:2719
#, python-format
msgid "In states %(vm_state)s/%(task_state)s, notRESIZED/None"
msgstr ""

#: nova/compute/manager.py:2727
#, python-format
msgid "Error auto-confirming resize: %(e)s. Will retry later."
msgstr ""

#: nova/compute/manager.py:2744
#, python-format
msgid ""
"Running instance usage audit for host %(host)s from %(begin_time)s to "
"%(end_time)s. %(number_instances)s instances."
msgstr ""

#: nova/compute/manager.py:2762
#, python-format
msgid "Failed to generate usage audit for instance on host %s"
msgstr ""

#: nova/compute/manager.py:2785
msgid "Updating bandwidth usage cache"
msgstr ""

#: nova/compute/manager.py:2850
msgid "Updating host status"
msgstr ""

#: nova/compute/manager.py:2876
#, python-format
msgid ""
"Found %(num_db_instances)s in the database and %(num_vm_instances)s on "
"the hypervisor."
msgstr ""

#: nova/compute/manager.py:2882 nova/compute/manager.py:2920
msgid "During sync_power_state the instance has a pending task. Skip."
msgstr ""

#: nova/compute/manager.py:2907
#, python-format
msgid ""
"During the sync_power process the instance has moved from host %(src)s to"
" host %(dst)s"
msgstr ""

#: nova/compute/manager.py:2944
msgid "Instance shutdown by itself. Calling the stop API."
msgstr ""

#: nova/compute/manager.py:2956 nova/compute/manager.py:2967
#: nova/compute/manager.py:2981
msgid "error during stop() in sync_power_state."
msgstr ""

#: nova/compute/manager.py:2961
msgid "Instance is paused or suspended unexpectedly. Calling the stop API."
msgstr ""

#: nova/compute/manager.py:2974
msgid "Instance is not stopped. Calling the stop API."
msgstr ""

#: nova/compute/manager.py:2990
msgid "Instance is not (soft-)deleted."
msgstr ""

#: nova/compute/manager.py:2998
msgid "FLAGS.reclaim_instance_interval <= 0, skipping..."
msgstr ""

#: nova/compute/manager.py:3011
msgid "Reclaiming deleted instance"
msgstr ""

#: nova/compute/manager.py:3060
#, python-format
msgid ""
"Detected instance with name label '%(name)s' which is marked as DELETED "
"but still present on host."
msgstr ""

#: nova/compute/manager.py:3067
#, python-format
msgid ""
"Destroying instance with name label '%(name)s' which is marked as DELETED"
" but still present on host."
msgstr ""

#: nova/compute/manager.py:3074
#, python-format
msgid "Unrecognized value '%(action)s' for FLAGS.running_deleted_instance_action"
msgstr ""

#: nova/compute/resource_tracker.py:151
msgid ""
"Host field should be not be set on the instance until resources have been"
" claimed."
msgstr ""

#: nova/compute/resource_tracker.py:168
#, python-format
msgid ""
"Attempting claim: memory %(memory_mb)d MB, disk %(disk_gb)d GB, VCPUs "
"%(vcpus)d"
msgstr ""

#: nova/compute/resource_tracker.py:210
#, python-format
msgid ""
"Total memory: %(total_mem)d MB, used: %(used_mem)d MB, free: %(free_mem)d"
" MB"
msgstr ""

#: nova/compute/resource_tracker.py:219
msgid "Memory limit not specified, defaulting to unlimited"
msgstr ""

#: nova/compute/resource_tracker.py:225
#, python-format
msgid "Memory limit: %(memory_mb_limit)d MB, free: %(free_ram_mb)d MB"
msgstr ""

#: nova/compute/resource_tracker.py:232
#, python-format
msgid ""
"Unable to claim resources.  Free memory %(free_ram_mb)d MB < requested "
"memory %(memory_mb)d MB"
msgstr ""

#: nova/compute/resource_tracker.py:241
#, python-format
msgid ""
"Total disk: %(total_disk)d GB, used: %(used_disk)d GB, free: "
"%(free_disk)d GB"
msgstr ""

#: nova/compute/resource_tracker.py:250
msgid "Disk limit not specified, defaulting to unlimited"
msgstr ""

#: nova/compute/resource_tracker.py:256
#, python-format
msgid "Disk limit: %(disk_gb_limit)d GB, free: %(free_disk_gb)d GB"
msgstr ""

#: nova/compute/resource_tracker.py:262
#, python-format
msgid ""
"Unable to claim resources.  Free disk %(free_disk_gb)d GB < requested "
"disk %(disk_gb)d GB"
msgstr ""

#: nova/compute/resource_tracker.py:273
#, python-format
msgid "Total VCPUs: %(total_vcpus)d, used: %(used_vcpus)d"
msgstr ""

#: nova/compute/resource_tracker.py:280
msgid "VCPU limit not specified, defaulting to unlimited"
msgstr ""

#: nova/compute/resource_tracker.py:284
#, python-format
msgid "CPU limit: %(vcpu_limit)d"
msgstr ""

#: nova/compute/resource_tracker.py:291
#, python-format
msgid ""
"Unable to claim resources.  Free CPU %(free_vcpus)d < requested CPU "
"%(vcpus)d"
msgstr ""

#: nova/compute/resource_tracker.py:310
#, python-format
msgid "Finishing claim: %s"
msgstr ""

#: nova/compute/resource_tracker.py:325
#, python-format
msgid "Aborting claim: %s"
msgstr ""

#: nova/compute/resource_tracker.py:363
msgid ""
"Virt driver does not support 'get_available_resource'  Compute tracking "
"is disabled."
msgstr ""

#: nova/compute/resource_tracker.py:401
#, python-format
msgid "Compute_service record created for %s "
msgstr ""

#: nova/compute/resource_tracker.py:406
#, python-format
msgid "Compute_service record updated for %s "
msgstr ""

#: nova/compute/resource_tracker.py:425
#, python-format
msgid "No service record for host %s"
msgstr ""

#: nova/compute/resource_tracker.py:435
#, python-format
msgid "Hypervisor: free ram (MB): %s"
msgstr ""

#: nova/compute/resource_tracker.py:436
#, python-format
msgid "Hypervisor: free disk (GB): %s"
msgstr ""

#: nova/compute/resource_tracker.py:441
#, python-format
msgid "Hypervisor: free VCPUs: %s"
msgstr ""

#: nova/compute/resource_tracker.py:443
msgid "Hypervisor: VCPU information unavailable"
msgstr ""

#: nova/compute/resource_tracker.py:450
#, python-format
msgid "Free ram (MB): %s"
msgstr ""

#: nova/compute/resource_tracker.py:451
#, python-format
msgid "Free disk (GB): %s"
msgstr ""

#: nova/compute/resource_tracker.py:456
#, python-format
msgid "Free VCPUS: %s"
msgstr ""

#: nova/compute/resource_tracker.py:458
msgid "Free VCPU information unavailable"
msgstr ""

#: nova/compute/resource_tracker.py:533
#, python-format
msgid "Missing keys: %s"
msgstr ""

#: nova/compute/rpcapi.py:44
msgid "No compute host specified"
msgstr ""

#: nova/compute/rpcapi.py:47
#, python-format
msgid "Unable to find host for Instance %s"
msgstr ""

#: nova/compute/utils.py:87
#, python-format
msgid "Using %(prefix)s instead of %(req_prefix)s"
msgstr ""

#: nova/console/manager.py:81 nova/console/vmrc_manager.py:71
msgid "Adding console"
msgstr ""

#: nova/console/manager.py:102 nova/console/vmrc_manager.py:123
#, python-format
msgid "Tried to remove non-existent console %(console_id)s."
msgstr ""

#: nova/console/vmrc_manager.py:126
#, python-format
msgid "Removing console %(console_id)s."
msgstr ""

#: nova/console/xvp.py:98
msgid "Rebuilding xvp conf"
msgstr ""

#: nova/console/xvp.py:116
#, python-format
msgid "Re-wrote %s"
msgstr ""

#: nova/console/xvp.py:121
msgid "Stopping xvp"
msgstr ""

#: nova/console/xvp.py:134
msgid "Starting xvp"
msgstr ""

#: nova/console/xvp.py:141
#, python-format
msgid "Error starting xvp: %s"
msgstr ""

#: nova/console/xvp.py:144
msgid "Restarting xvp"
msgstr ""

#: nova/console/xvp.py:146
msgid "xvp not running..."
msgstr ""

#: nova/consoleauth/manager.py:70
#, python-format
msgid "Received Token: %(token)s, %(token_dict)s)"
msgstr ""

#: nova/consoleauth/manager.py:75
#, python-format
msgid "Checking Token: %(token)s, %(token_valid)s)"
msgstr ""

#: nova/db/sqlalchemy/api.py:206
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: nova/db/sqlalchemy/api.py:2796
#, python-format
msgid "Change will make usage less than 0 for the following resources: %(unders)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:4697
msgid "Backend exists"
msgstr ""

#: nova/db/sqlalchemy/api.py:4717 nova/db/sqlalchemy/api.py:4743
#, python-format
msgid "No backend config with id %(sm_backend_id)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:4755
#, python-format
msgid "No backend config with sr uuid %(sr_uuid)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:4789
msgid "Flavor exists"
msgstr ""

#: nova/db/sqlalchemy/api.py:4804
#, python-format
msgid "%(sm_flavor_id) flavor not found"
msgstr ""

#: nova/db/sqlalchemy/api.py:4823
#, python-format
msgid "No sm_flavor called %(sm_flavor_id)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:4840
#, python-format
msgid "No sm_flavor called %(sm_flavor_label)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:4878
#, python-format
msgid "No sm_volume with id %(volume_id)s"
msgstr ""

#: nova/db/sqlalchemy/migration.py:74
msgid "version should be an integer"
msgstr ""

#: nova/db/sqlalchemy/migration.py:101
msgid "Upgrade DB using Essex release first."
msgstr ""

#: nova/db/sqlalchemy/session.py:162
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/083_quota_class.py:50
#: nova/db/sqlalchemy/migrate_repo/versions/092_add_instance_system_metadata.py:60
#: nova/db/sqlalchemy/migrate_repo/versions/097_quota_usages_reservations.py:53
#: nova/db/sqlalchemy/migrate_repo/versions/097_quota_usages_reservations.py:86
#: nova/db/sqlalchemy/migrate_repo/versions/115_make_user_quotas_key_and_value.py:74
#: nova/db/sqlalchemy/migrate_repo/versions/116_drop_user_quotas_key_and_value.py:97
#: nova/db/sqlalchemy/migrate_repo/versions/132_add_instance_type_projects.py:52
#, python-format
msgid "Table |%s| not created!"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/083_quota_class.py:62
msgid "quota_classes table not dropped"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/088_change_instance_id_to_uuid_in_block_device_mapping.py:56
#: nova/db/sqlalchemy/migrate_repo/versions/100_instance_metadata_uses_uuid.py:56
#: nova/db/sqlalchemy/migrate_repo/versions/101_security_group_instance_association_uses_uuid.py:56
#: nova/db/sqlalchemy/migrate_repo/versions/102_consoles_uses_uuid.py:56
#: nova/db/sqlalchemy/migrate_repo/versions/105_instance_info_caches_uses_uuid.py:44
#: nova/db/sqlalchemy/migrate_repo/versions/105_instance_info_caches_uses_uuid.py:67
#: nova/db/sqlalchemy/migrate_repo/versions/109_drop_dns_domains_project_id_fkey.py:43
#: nova/db/sqlalchemy/migrate_repo/versions/113_fixed_ips_uses_uuid.py:56
#: nova/db/sqlalchemy/migrate_repo/versions/113_fixed_ips_uses_uuid.py:87
#: nova/db/sqlalchemy/migrate_repo/versions/114_vifs_uses_uuid.py:56
#: nova/db/sqlalchemy/migrate_repo/versions/114_vifs_uses_uuid.py:87
msgid "foreign key constraint couldn't be removed"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/090_modify_volume_id_datatype.py:84
#: nova/db/sqlalchemy/migrate_repo/versions/090_modify_volume_id_datatype.py:128
#: nova/db/sqlalchemy/migrate_repo/versions/090_modify_volume_id_datatype.py:178
#: nova/db/sqlalchemy/migrate_repo/versions/090_modify_volume_id_datatype.py:236
msgid "Foreign Key constraint couldn't be removed"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/095_change_fk_instance_id_to_uuid.py:57
msgid "foreign key could not be dropped"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/095_change_fk_instance_id_to_uuid.py:91
msgid "foreign key could not be created"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/097_quota_usages_reservations.py:98
msgid "quota_usages table not dropped"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/097_quota_usages_reservations.py:105
msgid "reservations table not dropped"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/106_add_foreign_keys.py:45
#: nova/db/sqlalchemy/migrate_repo/versions/113_fixed_ips_uses_uuid.py:66
#: nova/db/sqlalchemy/migrate_repo/versions/113_fixed_ips_uses_uuid.py:107
#: nova/db/sqlalchemy/migrate_repo/versions/114_vifs_uses_uuid.py:66
#: nova/db/sqlalchemy/migrate_repo/versions/114_vifs_uses_uuid.py:107
msgid "foreign key constraint couldn't be created"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/106_add_foreign_keys.py:66
msgid "foreign key constraint couldn't be dropped"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/115_make_user_quotas_key_and_value.py:93
#: nova/db/sqlalchemy/migrate_repo/versions/116_drop_user_quotas_key_and_value.py:43
msgid "user_quotas table not dropped"
msgstr ""

#: nova/image/glance.py:143
#, python-format
msgid ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"%(extra)s."
msgstr ""

#: nova/image/s3.py:311
#, python-format
msgid "Failed to download %(image_location)s to %(image_path)s"
msgstr ""

#: nova/image/s3.py:328
#, python-format
msgid "Failed to decrypt %(image_location)s to %(image_path)s"
msgstr ""

#: nova/image/s3.py:338
#, python-format
msgid "Failed to untar %(image_location)s to %(image_path)s"
msgstr ""

#: nova/image/s3.py:348
#, python-format
msgid "Failed to upload %(image_location)s to %(image_path)s"
msgstr ""

#: nova/image/s3.py:372
#, python-format
msgid "Failed to decrypt private key: %s"
msgstr ""

#: nova/image/s3.py:379
#, python-format
msgid "Failed to decrypt initialization vector: %s"
msgstr ""

#: nova/image/s3.py:390
#, python-format
msgid "Failed to decrypt image file %(image_file)s: %(err)s"
msgstr ""

#: nova/image/s3.py:402
msgid "Unsafe filenames in image"
msgstr ""

#: nova/ipv6/account_identifier.py:38 nova/ipv6/rfc2462.py:34
#, python-format
msgid "Bad mac for to_global_ipv6: %s"
msgstr ""

#: nova/ipv6/account_identifier.py:40 nova/ipv6/rfc2462.py:36
#, python-format
msgid "Bad prefix for to_global_ipv6: %s"
msgstr ""

#: nova/ipv6/account_identifier.py:42
#, python-format
msgid "Bad project_id for to_global_ipv6: %s"
msgstr ""

#: nova/network/api.py:54
msgid "instance is a required argument to use @refresh_cache"
msgstr ""

#: nova/network/api.py:81
#, python-format
msgid "args: %s"
msgstr ""

#: nova/network/api.py:82
#, python-format
msgid "kwargs: %s"
msgstr ""

#: nova/network/api.py:170
#, python-format
msgid "re-assign floating IP %(address)s from instance %(instance_id)s"
msgstr ""

#: nova/network/ldapdns.py:317
msgid "This driver only supports type 'a' entries."
msgstr ""

#: nova/network/linux_net.py:179
#, python-format
msgid "Attempted to remove chain %s which does not exist"
msgstr ""

#: nova/network/linux_net.py:214
#, python-format
msgid "Unknown chain: %r"
msgstr ""

#: nova/network/linux_net.py:239
#, python-format
msgid ""
"Tried to remove rule that was not there: %(chain)r %(rule)r %(wrap)r "
"%(top)r"
msgstr ""

#: nova/network/linux_net.py:374
msgid "IPTablesManager.apply completed with success"
msgstr ""

#: nova/network/linux_net.py:580
#, python-format
msgid "arping error for ip %s"
msgstr ""

#: nova/network/linux_net.py:790
#, python-format
msgid "Pid %d is stale, skip killing dnsmasq"
msgstr ""

#: nova/network/linux_net.py:830
#, python-format
msgid "Hupping dnsmasq threw %s"
msgstr ""

#: nova/network/linux_net.py:832
#, python-format
msgid "Pid %d is stale, relaunching dnsmasq"
msgstr ""

#: nova/network/linux_net.py:895
#, python-format
msgid "killing radvd threw %s"
msgstr ""

#: nova/network/linux_net.py:897
#, python-format
msgid "Pid %d is stale, relaunching radvd"
msgstr ""

#: nova/network/linux_net.py:1127
#, python-format
msgid "Starting VLAN inteface %s"
msgstr ""

#: nova/network/linux_net.py:1163
#, python-format
msgid "Starting Bridge interface for %s"
msgstr ""

#: nova/network/linux_net.py:1206
#, python-format
msgid "Failed to add interface: %s"
msgstr ""

#: nova/network/linux_net.py:1307
#, python-format
msgid "Starting bridge %s "
msgstr ""

#: nova/network/linux_net.py:1315
#, python-format
msgid "Done starting bridge %s"
msgstr ""

#: nova/network/linux_net.py:1334
#, python-format
msgid "Failed unplugging gateway interface '%s'"
msgstr ""

#: nova/network/linux_net.py:1336
#, python-format
msgid "Unplugged gateway interface '%s'"
msgstr ""

#: nova/network/manager.py:284
#, python-format
msgid "Fixed ip %(fixed_ip_id)s not found"
msgstr ""

#: nova/network/manager.py:293 nova/network/manager.py:552
#, python-format
msgid "Interface %(interface)s not found"
msgstr ""

#: nova/network/manager.py:308
#, python-format
msgid "floating IP allocation for instance |%s|"
msgstr ""

#: nova/network/manager.py:372
msgid "Floating IP is not associated. Ignore."
msgstr ""

#: nova/network/manager.py:390
#, python-format
msgid "Address |%(address)s| is not allocated"
msgstr ""

#: nova/network/manager.py:394
#, python-format
msgid "Address |%(address)s| is not allocated to your project |%(project)s|"
msgstr ""

#: nova/network/manager.py:415
#, python-format
msgid "Quota exceeded for %(pid)s, tried to allocate floating IP"
msgstr ""

#: nova/network/manager.py:476
msgid "Failed to update usages deallocating floating IP"
msgstr ""

#: nova/network/manager.py:673
#, python-format
msgid "Starting migration network for instance %(instance_uuid)s"
msgstr ""

#: nova/network/manager.py:680
#, python-format
msgid ""
"Floating ip address |%(address)s| no longer belongs to instance "
"%(instance_uuid)s. Will notmigrate it "
msgstr ""

#: nova/network/manager.py:706
#, python-format
msgid "Finishing migration network for instance %(instance_uuid)s"
msgstr ""

#: nova/network/manager.py:714
#, python-format
msgid ""
"Floating ip address |%(address)s| no longer belongs to instance "
"%(instance_uuid)s. Will notsetup it."
msgstr ""

#: nova/network/manager.py:761
#, python-format
msgid ""
"Database inconsistency: DNS domain |%s| is registered in the Nova db but "
"not visible to either the floating or instance DNS driver. It will be "
"ignored."
msgstr ""

#: nova/network/manager.py:807
#, python-format
msgid "Domain |%(domain)s| already exists, changing zone to |%(av_zone)s|."
msgstr ""

#: nova/network/manager.py:817
#, python-format
msgid "Domain |%(domain)s| already exists, changing project to |%(project)s|."
msgstr ""

#: nova/network/manager.py:931
#, python-format
msgid "Disassociated %s stale fixed ip(s)"
msgstr ""

#: nova/network/manager.py:935
msgid "setting network host"
msgstr ""

#: nova/network/manager.py:1049
msgid "network allocations"
msgstr ""

#: nova/network/manager.py:1054
#, python-format
msgid "networks retrieved for instance: |%(networks)s|"
msgstr ""

#: nova/network/manager.py:1084
msgid "network deallocation for instance"
msgstr ""

#: nova/network/manager.py:1307
#, python-format
msgid ""
"instance-dns-zone is |%(domain)s|, which is in availability zone "
"|%(zone)s|. Instance is in zone |%(zone2)s|. No DNS record will be "
"created."
msgstr ""

#: nova/network/manager.py:1388
#, python-format
msgid "Unable to release %s because vif doesn't exist."
msgstr ""

#: nova/network/manager.py:1409
#, python-format
msgid "Leased IP |%(address)s|"
msgstr ""

#: nova/network/manager.py:1413
#, python-format
msgid "IP %s leased that is not associated"
msgstr ""

#: nova/network/manager.py:1421
#, python-format
msgid "IP |%s| leased that isn't allocated"
msgstr ""

#: nova/network/manager.py:1426
#, python-format
msgid "Released IP |%(address)s|"
msgstr ""

#: nova/network/manager.py:1430
#, python-format
msgid "IP %s released that is not associated"
msgstr ""

#: nova/network/manager.py:1433
#, python-format
msgid "IP %s released that was not leased"
msgstr ""

#: nova/network/manager.py:1452
#, python-format
msgid "%s must be an integer"
msgstr ""

#: nova/network/manager.py:1476
msgid "Maximum allowed length for 'label' is 255."
msgstr ""

#: nova/network/manager.py:1496
#, python-format
msgid ""
"Subnet(s) too large, defaulting to /%s.  To override, specify "
"network_size flag."
msgstr ""

#: nova/network/manager.py:1577
msgid "cidr already in use"
msgstr ""

#: nova/network/manager.py:1580
#, python-format
msgid "requested cidr (%(cidr)s) conflicts with existing supernet (%(super)s)"
msgstr ""

#: nova/network/manager.py:1591
#, python-format
msgid ""
"requested cidr (%(cidr)s) conflicts with existing smaller cidr "
"(%(smaller)s)"
msgstr ""

#: nova/network/manager.py:1650
msgid "Network already exists!"
msgstr ""

#: nova/network/manager.py:1670
#, python-format
msgid "Network must be disassociated from project %s before delete"
msgstr ""

#: nova/network/manager.py:2136
msgid ""
"The sum between the number of networks and the vlan start cannot be "
"greater than 4094"
msgstr ""

#: nova/network/manager.py:2143
#, python-format
msgid ""
"The network range is not big enough to fit %(num_networks)s. Network size"
" is %(network_size)s"
msgstr ""

#: nova/network/minidns.py:65
msgid "This driver only supports type 'a'"
msgstr ""

#: nova/network/model.py:337
msgid "v4 subnets are required for legacy nw_info"
msgstr ""

#: nova/network/quantum/nova_ipam_lib.py:75
msgid "Error creating network entry"
msgstr ""

#: nova/network/quantum/nova_ipam_lib.py:90
#, python-format
msgid "No network with net_id = %s"
msgstr ""

#: nova/network/quantum/nova_ipam_lib.py:256
#, python-format
msgid "No fixed IPs to deallocate for vif %s"
msgstr ""

#: nova/network/quantumv2/__init__.py:41
msgid "_get_auth_token() failed"
msgstr ""

#: nova/network/quantumv2/api.py:98
#, python-format
msgid "allocate_for_instance() for %s"
msgstr ""

#: nova/network/quantumv2/api.py:101
#, python-format
msgid "empty project id for instance %s"
msgstr ""

#: nova/network/quantumv2/api.py:154
#, python-format
msgid "Fail to delete port %(portid)s with failure: %(exception)s"
msgstr ""

#: nova/network/quantumv2/api.py:166
#, python-format
msgid "deallocate_for_instance() for %s"
msgstr ""

#: nova/network/quantumv2/api.py:175
#, python-format
msgid "Failed to delete quantum port %(portid)s "
msgstr ""

#: nova/network/quantumv2/api.py:185
#, python-format
msgid "get_instance_nw_info() for %s"
msgstr ""

#: nova/network/quantumv2/api.py:200
#, python-format
msgid "validate_networks() for %s"
msgstr ""

#: nova/network/quantumv2/api.py:452
#, python-format
msgid "Multiple floating IP pools matches found for name '%s'"
msgstr ""

#: nova/openstack/common/lockutils.py:98
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: nova/openstack/common/lockutils.py:184
#, python-format
msgid "Got semaphore \"%(lock)s\" for method \"%(method)s\"..."
msgstr ""

#: nova/openstack/common/lockutils.py:188
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\" for method \"%(method)s\"..."
msgstr ""

#: nova/openstack/common/lockutils.py:216
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s for method \"%(method)s\"..."
msgstr ""

#: nova/openstack/common/log.py:177
#, python-format
msgid "Deprecated Config: %s"
msgstr ""

#: nova/openstack/common/log.py:309
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: nova/openstack/common/log.py:467
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: nova/openstack/common/policy.py:394
#, python-format
msgid "Failed to understand rule %(rule)s"
msgstr ""

#: nova/openstack/common/policy.py:404
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: nova/openstack/common/policy.py:679
#, python-format
msgid "Failed to understand rule %(rule)r"
msgstr ""

#: nova/openstack/common/notifier/api.py:125
#, python-format
msgid "%s not in valid priorities"
msgstr ""

#: nova/openstack/common/notifier/api.py:141
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""

#: nova/openstack/common/notifier/api.py:170
#, python-format
msgid "Failed to load notifier %s. These notifications will not be sent."
msgstr ""

#: nova/openstack/common/notifier/rabbit_notifier.py:45
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr ""

#: nova/openstack/common/plugin/pluginmanager.py:64
#, python-format
msgid "Failed to load plugin %(plug)s: %(exc)s"
msgstr ""

#: nova/openstack/common/rpc/amqp.py:209
#, python-format
msgid "unpacked context: %s"
msgstr ""

#: nova/openstack/common/rpc/amqp.py:253
#, python-format
msgid "received %s"
msgstr ""

#: nova/openstack/common/rpc/amqp.py:259
#, python-format
msgid "no method for message: %s"
msgstr ""

#: nova/openstack/common/rpc/amqp.py:260
#, python-format
msgid "No method for message: %s"
msgstr ""

#: nova/openstack/common/rpc/amqp.py:352
#, python-format
msgid "Making asynchronous call on %s ..."
msgstr ""

#: nova/openstack/common/rpc/amqp.py:355
#, python-format
msgid "MSG_ID is %s"
msgstr ""

#: nova/openstack/common/rpc/amqp.py:377
#, python-format
msgid "Making asynchronous cast on %s..."
msgstr ""

#: nova/openstack/common/rpc/amqp.py:385
msgid "Making asynchronous fanout cast..."
msgstr ""

#: nova/openstack/common/rpc/amqp.py:411
#, python-format
msgid "Sending %(event_type)s on %(topic)s"
msgstr ""

#: nova/openstack/common/rpc/common.py:34
msgid "An unknown RPC related exception occurred."
msgstr ""

#: nova/openstack/common/rpc/common.py:64
#, python-format
msgid ""
"Remote error: %(exc_type)s %(value)s\n"
"%(traceback)s."
msgstr ""

#: nova/openstack/common/rpc/common.py:81
msgid "Timeout while waiting on RPC response."
msgstr ""

#: nova/openstack/common/rpc/common.py:85
msgid "Invalid reuse of an RPC connection."
msgstr ""

#: nova/openstack/common/rpc/common.py:89
#, python-format
msgid "Specified RPC version, %(version)s, not supported by this endpoint."
msgstr ""

#: nova/openstack/common/rpc/common.py:206
#, python-format
msgid "Returning exception %s to caller"
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:168
#: nova/openstack/common/rpc/impl_qpid.py:144
msgid "Failed to process message... skipping it."
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:468
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:490
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:527
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:543
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:595
#: nova/openstack/common/rpc/impl_qpid.py:403
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:613
#: nova/openstack/common/rpc/impl_qpid.py:418
#, python-format
msgid "Timed out waiting for RPC response: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:617
#: nova/openstack/common/rpc/impl_qpid.py:422
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:651
#: nova/openstack/common/rpc/impl_qpid.py:452
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr ""

#: nova/openstack/common/rpc/impl_qpid.py:359
#, python-format
msgid "Unable to connect to AMQP server: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_qpid.py:364
#, python-format
msgid "Connected to AMQP server on %s"
msgstr ""

#: nova/openstack/common/rpc/impl_qpid.py:372
msgid "Re-established AMQP queues"
msgstr ""

#: nova/openstack/common/rpc/impl_qpid.py:430
msgid "Error processing message.  Skipping it."
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:89
msgid "JSON serialization failed."
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:97
#, python-format
msgid "Deserializing: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:133
#, python-format
msgid "Connecting to %(addr)s with %(type)s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:134
#, python-format
msgid "-> Subscribed to %(subscribe)s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:135
#, python-format
msgid "-> bind: %(bind)s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:143
msgid "Could not open socket."
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:155
#, python-format
msgid "Subscribing to %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:193
msgid "You cannot recv on this socket."
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:198
msgid "You cannot send on this socket."
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:251
#, python-format
msgid "Running func with context: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:276
msgid "Sending reply"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:344
msgid "Registering reactor"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:356
msgid "In reactor registered"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:371
msgid "Out reactor registered"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:375
msgid "Consuming socket"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:422
#, python-format
msgid "CONSUMER GOT %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:432
#, python-format
msgid "->response->%s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:442
#, python-format
msgid "Created topic proxy: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:449
#, python-format
msgid "ROUTER RELAY-OUT START %(data)s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:451
#, python-format
msgid "ROUTER RELAY-OUT SUCCEEDED %(data)s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:467
#, python-format
msgid "CONSUMER RECEIVED DATA: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:469
#, python-format
msgid "ROUTER RELAY-OUT %(data)s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:495
#, python-format
msgid "Create Consumer for topic (%(topic)s)"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:511
#, python-format
msgid "Consumer is a zmq.%s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:554
msgid "Creating payload"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:567
msgid "Creating queue socket for reply waiter"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:578
msgid "Sending cast"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:581
msgid "Cast sent; Waiting reply"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:584
#, python-format
msgid "Received message: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:585
msgid "Unpacking response"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:612
#, python-format
msgid "%(msg)s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:615
#, python-format
msgid "Sending message(s) to: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:619
msgid "No matchmaker results. Not casting."
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:709
msgid ""
"Matchmaker could not be loaded.\n"
"rpc_zmq_matchmaker is not a class."
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:711
msgid "Error loading Matchmaker."
msgstr ""

#: nova/openstack/common/rpc/matchmaker.py:45
msgid "Match not found by MatchMaker."
msgstr ""

#: nova/openstack/common/rpc/matchmaker.py:177
#: nova/openstack/common/rpc/matchmaker.py:195
#, python-format
msgid "No key defining hosts for topic '%s', see ringfile"
msgstr ""

#: nova/scheduler/chance.py:49
msgid "Is the appropriate service running?"
msgstr ""

#: nova/scheduler/chance.py:54
msgid "Could not find another compute"
msgstr ""

#: nova/scheduler/driver.py:64
msgid "Exception during scheduler.run_instance"
msgstr ""

#: nova/scheduler/driver.py:68 nova/scheduler/manager.py:184
#, python-format
msgid "Setting instance to %(state)s state."
msgstr ""

#: nova/scheduler/driver.py:110
#, python-format
msgid "Casted '%(method)s' to compute '%(host)s'"
msgstr ""

#: nova/scheduler/driver.py:125
#, python-format
msgid "Casted '%(method)s' to %(topic)s '%(host)s'"
msgstr ""

#: nova/scheduler/driver.py:173
msgid "Driver must implement schedule_prep_resize"
msgstr ""

#: nova/scheduler/driver.py:181
msgid "Driver must implement schedule_run_instance"
msgstr ""

#: nova/scheduler/driver.py:313
#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s to %(dest)s: Lack of "
"memory(host:%(avail)s <= instance:%(mem_inst)s)"
msgstr ""

#: nova/scheduler/filter_scheduler.py:57
#, python-format
msgid "Attempting to build %(num_instances)d instance(s)"
msgstr ""

#: nova/scheduler/filter_scheduler.py:192
msgid "Invalid value for 'scheduler_max_attempts', must be >= 1"
msgstr ""

#: nova/scheduler/filter_scheduler.py:219
#, python-format
msgid ""
"Exceeded max scheduling attempts %(max_attempts)d for instance "
"%(instance_uuid)s"
msgstr ""

#: nova/scheduler/filter_scheduler.py:230
msgid "Scheduler only understands Compute nodes (for now)"
msgstr ""

#: nova/scheduler/filter_scheduler.py:282
#, python-format
msgid "Filtered %(hosts)s"
msgstr ""

#: nova/scheduler/filter_scheduler.py:292
#, python-format
msgid "Weighted %(weighted_host)s"
msgstr ""

#: nova/scheduler/host_manager.py:237
#, python-format
msgid "Host filter fails for ignored host %(host)s"
msgstr ""

#: nova/scheduler/host_manager.py:244
#, python-format
msgid "Host filter fails for non-forced host %(host)s"
msgstr ""

#: nova/scheduler/host_manager.py:250
#, python-format
msgid "Host filter function %(func)s failed for %(host)s"
msgstr ""

#: nova/scheduler/host_manager.py:256
#, python-format
msgid "Host filter passes for %(host)s"
msgstr ""

#: nova/scheduler/host_manager.py:318
#, python-format
msgid "Received %(service_name)s service update from %(host)s."
msgstr ""

#: nova/scheduler/host_manager.py:341
msgid "host_manager only implemented for 'compute'"
msgstr ""

#: nova/scheduler/host_manager.py:351
#, python-format
msgid "No service for compute ID %s"
msgstr ""

#: nova/scheduler/manager.py:168
#, python-format
msgid "Failed to schedule_%(method)s: %(ex)s"
msgstr ""

#: nova/scheduler/scheduler_options.py:69
#, python-format
msgid "Could not stat scheduler options file %(filename)s: '%(e)s'"
msgstr ""

#: nova/scheduler/scheduler_options.py:78
#, python-format
msgid "Could not decode scheduler options: '%(e)s'"
msgstr ""

#: nova/scheduler/filters/aggregate_instance_extra_specs.py:49
#: nova/scheduler/filters/aggregate_instance_extra_specs.py:56
#: nova/scheduler/filters/compute_capabilities_filter.py:48
#, python-format
msgid "%(host_state)s fails instance_type extra_specs requirements"
msgstr ""

#: nova/scheduler/filters/compute_filter.py:38
#, python-format
msgid "%(host_state)s is disabled or has not been heard from in a while"
msgstr ""

#: nova/scheduler/filters/compute_filter.py:42
#, python-format
msgid "%(host_state)s is disabled via capabilities"
msgstr ""

#: nova/scheduler/filters/core_filter.py:45
msgid "VCPUs not set; assuming CPU collection broken"
msgstr ""

#: nova/scheduler/filters/disk_filter.py:47
#, python-format
msgid ""
"%(host_state)s does not have %(requested_disk)s MB usable disk, it only "
"has %(usable_disk_mb)s MB usable disk."
msgstr ""

#: nova/scheduler/filters/image_props_filter.py:48
#, python-format
msgid ""
"Instance contains properties %(image_props)s, but no corresponding "
"capabilities are advertised by the compute node"
msgstr ""

#: nova/scheduler/filters/image_props_filter.py:61
#, python-format
msgid ""
"Instance properties %(image_props)s are satisfied by compute host "
"capabilities %(capabilities)s"
msgstr ""

#: nova/scheduler/filters/image_props_filter.py:66
#, python-format
msgid ""
"Instance contains properties %(image_props)s that are not provided by the"
" compute node capabilities %(capabilities)s"
msgstr ""

#: nova/scheduler/filters/image_props_filter.py:82
#, python-format
msgid "%(host_state)s does not support requested instance_properties"
msgstr ""

#: nova/scheduler/filters/io_ops_filter.py:42
#, python-format
msgid ""
"%(host_state)s fails I/O ops check: Max IOs per host is set to "
"%(max_io_ops)s"
msgstr ""

#: nova/scheduler/filters/num_instances_filter.py:39
#, python-format
msgid ""
"%(host_state)s fails num_instances check: Max instances per host is set "
"to %(max_instances)s"
msgstr ""

#: nova/scheduler/filters/ram_filter.py:46
#, python-format
msgid ""
"%(host_state)s does not have %(requested_ram)s MB usable ram, it only has"
" %(usable_ram)s MB usable ram."
msgstr ""

#: nova/scheduler/filters/retry_filter.py:38
#, python-format
msgid "Previously tried hosts: %(hosts)s.  (host=%(host)s)"
msgstr ""

#: nova/scheduler/filters/trusted_filter.py:201
#, python-format
msgid "TCP: trust state of %(host)s:%(level)s(%(trust)s)"
msgstr ""

#: nova/tests/fake_ldap.py:34
msgid "Attempted to instantiate singleton"
msgstr ""

#: nova/tests/fake_utils.py:72
#, python-format
msgid "Faking execution of cmd (subprocess): %s"
msgstr ""

#: nova/tests/fake_utils.py:80
#, python-format
msgid "Faked command matched %s"
msgstr ""

#: nova/tests/fake_utils.py:96
#, python-format
msgid "Faked command raised an exception %s"
msgstr ""

#: nova/tests/fake_utils.py:101
#, python-format
msgid "Reply to faked command is stdout='%(stdout)s' stderr='%(stderr)s'"
msgstr ""

#: nova/tests/fake_volume.py:180 nova/volume/cinder.py:159
msgid "status must be available"
msgstr ""

#: nova/tests/fake_volume.py:184 nova/volume/cinder.py:162
msgid "already attached"
msgstr ""

#: nova/tests/fake_volume.py:189 nova/volume/cinder.py:168
msgid "already detached"
msgstr ""

#: nova/tests/fakelibvirt.py:849
msgid "Please extend mock libvirt module to support flags"
msgstr ""

#: nova/tests/fakelibvirt.py:853
msgid "Expected a list for 'auth' parameter"
msgstr ""

#: nova/tests/fakelibvirt.py:857
msgid "Expected a function in 'auth[0]' parameter"
msgstr ""

#: nova/tests/fakelibvirt.py:861
msgid "Expected a function in 'auth[1]' parameter"
msgstr ""

#: nova/tests/test_misc.py:62
#, python-format
msgid ""
"The following migrations are missing a downgrade:\n"
"\t%s"
msgstr ""

#: nova/tests/test_nova_manage.py:202
msgid "id"
msgstr ""

#: nova/tests/test_nova_manage.py:203
msgid "IPv4"
msgstr ""

#: nova/tests/test_nova_manage.py:204
msgid "IPv6"
msgstr ""

#: nova/tests/test_nova_manage.py:205
msgid "start address"
msgstr ""

#: nova/tests/test_nova_manage.py:206
msgid "DNS1"
msgstr ""

#: nova/tests/test_nova_manage.py:207
msgid "DNS2"
msgstr ""

#: nova/tests/test_nova_manage.py:208
msgid "VlanID"
msgstr ""

#: nova/tests/test_nova_manage.py:209
msgid "project"
msgstr ""

#: nova/tests/test_nova_manage.py:210
msgid "uuid"
msgstr ""

#: nova/tests/test_xenapi.py:722
#, python-format
msgid "Creating files in %s to simulate guest agent"
msgstr ""

#: nova/tests/test_xenapi.py:733
#, python-format
msgid "Removing simulated guest agent files in %s"
msgstr ""

#: nova/tests/api/test_auth.py:79
msgid "200 Role Match"
msgstr ""

#: nova/tests/api/test_auth.py:81
msgid "200 No Roles"
msgstr ""

#: nova/tests/api/test_auth.py:84
msgid "unexpected role header"
msgstr ""

#: nova/tests/api/openstack/compute/test_servers.py:2996
msgid ""
"Quota exceeded for instances: Requested 1, but already used 10 of 10 "
"instances"
msgstr ""

#: nova/tests/api/openstack/compute/test_servers.py:3001
msgid "Quota exceeded for ram: Requested 4096, but already used 8192 of 10240 ram"
msgstr ""

#: nova/tests/api/openstack/compute/test_servers.py:3006
msgid "Quota exceeded for cores: Requested 2, but already used 9 of 10 cores"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:56
#, python-format
msgid "_create: %s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:65
#, python-format
msgid "_delete: %s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:74
#, python-format
msgid "_get: %s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:84
#, python-format
msgid "_get_all: %s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:128
#, python-format
msgid "test_snapshot_create: param=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:137
#, python-format
msgid "test_snapshot_create: resp_dict=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:159
#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:185
#, python-format
msgid "test_snapshot_create_force: param=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:168
#, python-format
msgid "test_snapshot_create_force: resp_dict=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:221
#, python-format
msgid "test_snapshot_show: resp=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:247
#, python-format
msgid "test_snapshot_detail: resp_dict=%s"
msgstr ""

#: nova/tests/compute/test_compute.py:633
#: nova/tests/compute/test_compute.py:651
#: nova/tests/compute/test_compute.py:687
#: nova/tests/compute/test_compute.py:712
#: nova/tests/compute/test_compute.py:2403
#, python-format
msgid "Running instances: %s"
msgstr ""

#: nova/tests/compute/test_compute.py:639
#: nova/tests/compute/test_compute.py:674
#: nova/tests/compute/test_compute.py:700
#: nova/tests/compute/test_compute.py:730
#, python-format
msgid "After terminating instances: %s"
msgstr ""

#: nova/tests/compute/test_compute.py:1107
msgid "Internal error"
msgstr ""

#: nova/tests/compute/test_compute.py:2414
#, python-format
msgid "After force-killing instances: %s"
msgstr ""

#: nova/tests/hyperv/hypervutils.py:141 nova/virt/hyperv/vmops.py:471
#, python-format
msgid "Failed to change vm state of %(vm_name)s to %(req_state)s"
msgstr ""

#: nova/tests/hyperv/hypervutils.py:192 nova/virt/hyperv/vmops.py:406
#, python-format
msgid "Failed to destroy vm %s"
msgstr ""

#: nova/tests/hyperv/hypervutils.py:235 nova/virt/hyperv/snapshotops.py:92
#, python-format
msgid "Failed to get info for disk %s"
msgstr ""

#: nova/tests/integrated/test_api_samples.py:140
#, python-format
msgid "Result: %(result)s is not a dict."
msgstr ""

#: nova/tests/integrated/test_api_samples.py:144
#, python-format
msgid ""
"Key mismatch:\n"
"%(ex_keys)s\n"
"%(res_keys)s"
msgstr ""

#: nova/tests/integrated/test_api_samples.py:152
#, python-format
msgid "Result: %(result)s is not a list."
msgstr ""

#: nova/tests/integrated/test_api_samples.py:155
#, python-format
msgid ""
"Length mismatch: %(result)s\n"
"%(expected)s."
msgstr ""

#: nova/tests/integrated/test_api_samples.py:166
#, python-format
msgid "Result: %(res_obj)s not in %(expected)s."
msgstr ""

#: nova/tests/integrated/test_api_samples.py:183
#: nova/tests/integrated/test_api_samples.py:196
#, python-format
msgid ""
"Values do not match:\n"
"%(expected)s\n"
"%(result)s"
msgstr ""

#: nova/tests/integrated/test_login.py:31
#, python-format
msgid "flavor: %s"
msgstr ""

#: nova/tests/integrated/api/client.py:38
#, python-format
msgid ""
"%(message)s\n"
"Status Code: %(_status)s\n"
"Body: %(_body)s"
msgstr ""

#: nova/tests/integrated/api/client.py:47
msgid "Authentication error"
msgstr ""

#: nova/tests/integrated/api/client.py:55
msgid "Authorization error"
msgstr ""

#: nova/tests/integrated/api/client.py:63
msgid "Item not found"
msgstr ""

#: nova/tests/integrated/api/client.py:105
#, python-format
msgid "Doing %(method)s on %(relative_url)s"
msgstr ""

#: nova/tests/integrated/api/client.py:107
#, python-format
msgid "Body: %s"
msgstr ""

#: nova/tests/integrated/api/client.py:125
#, python-format
msgid "%(auth_uri)s => code %(http_status)s"
msgstr ""

#: nova/tests/integrated/api/client.py:155
#, python-format
msgid "%(relative_uri)s => code %(http_status)s"
msgstr ""

#: nova/tests/integrated/api/client.py:165
msgid "Unexpected status code"
msgstr ""

#: nova/tests/integrated/api/client.py:172
#, python-format
msgid "Decoding JSON: %s"
msgstr ""

#: nova/virt/configdrive.py:77
#, python-format
msgid "Added %(filepath)s to config drive"
msgstr ""

#: nova/virt/firewall.py:176 nova/virt/libvirt/firewall.py:249
msgid "Attempted to unfilter instance which is not filtered"
msgstr ""

#: nova/virt/firewall.py:187
msgid "Filters added to instance"
msgstr ""

#: nova/virt/firewall.py:189
msgid "Provider Firewall Rules refreshed"
msgstr ""

#: nova/virt/firewall.py:357
#, python-format
msgid "Adding security group rule: %r"
msgstr ""

#: nova/virt/firewall.py:489 nova/virt/xenapi/firewall.py:80
#, python-format
msgid "Adding provider rule: %s"
msgstr ""

#: nova/virt/images.py:114
msgid "Snapshot list encountered but no header found!"
msgstr ""

#: nova/virt/images.py:213
msgid "'qemu-img info' parsing failed."
msgstr ""

#: nova/virt/images.py:219
#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr ""

#: nova/virt/images.py:230
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr ""

#: nova/virt/baremetal/dom.py:93
msgid "No domains exist."
msgstr ""

#: nova/virt/baremetal/dom.py:95
#, python-format
msgid "============= initial domains =========== : %s"
msgstr ""

#: nova/virt/baremetal/dom.py:99
msgid "Building domain: to be removed"
msgstr ""

#: nova/virt/baremetal/dom.py:103
msgid "Not running domain: remove"
msgstr ""

#: nova/virt/baremetal/dom.py:111
msgid "domain running on an unknown node: discarded"
msgstr ""

#: nova/virt/baremetal/dom.py:127
#, python-format
msgid "No such domain (%s)"
msgstr ""

#: nova/virt/baremetal/dom.py:134
#, python-format
msgid "Failed power down Bare-metal node %s"
msgstr ""

#: nova/virt/baremetal/dom.py:143
msgid "deactivate -> activate fails"
msgstr ""

#: nova/virt/baremetal/dom.py:153
msgid "destroy_domain: no such domain"
msgstr ""

#: nova/virt/baremetal/dom.py:154
#, python-format
msgid "No such domain %s"
msgstr ""

#: nova/virt/baremetal/dom.py:161
#, python-format
msgid "Domains: %s"
msgstr ""

#: nova/virt/baremetal/dom.py:164
#, python-format
msgid "After storing domains: %s"
msgstr ""

#: nova/virt/baremetal/dom.py:167
msgid "deactivation/removing domain failed"
msgstr ""

#: nova/virt/baremetal/dom.py:174
msgid "===== Domain is being created ====="
msgstr ""

#: nova/virt/baremetal/dom.py:177
msgid "Same domain name already exists"
msgstr ""

#: nova/virt/baremetal/dom.py:179
msgid "create_domain: before get_idle_node"
msgstr ""

#: nova/virt/baremetal/dom.py:196
#, python-format
msgid "Created new domain: %s"
msgstr ""

#: nova/virt/baremetal/dom.py:211
#, python-format
msgid "Failed to boot Bare-metal node %s"
msgstr ""

#: nova/virt/baremetal/dom.py:220
msgid "No such domain exists"
msgstr ""

#: nova/virt/baremetal/dom.py:224
#, python-format
msgid "change_domain_state: to new state %s"
msgstr ""

#: nova/virt/baremetal/dom.py:231
#, python-format
msgid "Stored fake domains to the file: %s"
msgstr ""

#: nova/virt/baremetal/dom.py:242
msgid "domain does not exist"
msgstr ""

#: nova/virt/baremetal/driver.py:116
#, python-format
msgid "Error encountered when destroying instance '%(name)s': %(ex)s"
msgstr ""

#: nova/virt/baremetal/driver.py:130
#, python-format
msgid "instance %(instance_name)s: deleting instance files %(target)s"
msgstr ""

#: nova/virt/baremetal/driver.py:157
#, python-format
msgid "instance %s: rebooted"
msgstr ""

#: nova/virt/baremetal/driver.py:161
msgid "_wait_for_reboot failed"
msgstr ""

#: nova/virt/baremetal/driver.py:190
#, python-format
msgid "instance %s: rescued"
msgstr ""

#: nova/virt/baremetal/driver.py:194
msgid "_wait_for_rescue failed"
msgstr ""

#: nova/virt/baremetal/driver.py:211
msgid "<============= spawn of baremetal =============>"
msgstr ""

#: nova/virt/baremetal/driver.py:224
#, python-format
msgid "instance %s: is building"
msgstr ""

#: nova/virt/baremetal/driver.py:230
msgid "Key is injected but instance is not running yet"
msgstr ""

#: nova/virt/baremetal/driver.py:239
#, python-format
msgid "instance %s: booted"
msgstr ""

#: nova/virt/baremetal/driver.py:246
#, python-format
msgid "~~~~~~ current state = %s ~~~~~~"
msgstr ""

#: nova/virt/baremetal/driver.py:248
#, python-format
msgid "instance %s spawned successfully"
msgstr ""

#: nova/virt/baremetal/driver.py:251
#, python-format
msgid "instance %s:not booted"
msgstr ""

#: nova/virt/baremetal/driver.py:254
msgid "Baremetal assignment is overcommitted."
msgstr ""

#: nova/virt/baremetal/driver.py:338
#, python-format
msgid "instance %s: Creating image"
msgstr ""

#: nova/virt/baremetal/driver.py:456
#, python-format
msgid "instance %(inst_name)s: injecting %(injection)s into image %(img_id)s"
msgstr ""

#: nova/virt/baremetal/driver.py:466
#, python-format
msgid ""
"instance %(inst_name)s: ignoring error injecting data into image "
"%(img_id)s (%(e)s)"
msgstr ""

#: nova/virt/baremetal/driver.py:512
#, python-format
msgid "instance %s: starting toXML method"
msgstr ""

#: nova/virt/baremetal/driver.py:515
#, python-format
msgid "instance %s: finished toXML method"
msgstr ""

#: nova/virt/baremetal/driver.py:559 nova/virt/hyperv/hostops.py:43
#: nova/virt/libvirt/driver.py:1986
msgid ""
"Cannot get the number of cpu, because this function is not implemented "
"for this platform. This error can be safely ignored for now."
msgstr ""

#: nova/virt/baremetal/driver.py:682
#, python-format
msgid "#### RLK: cpu_arch = %s "
msgstr ""

#: nova/virt/baremetal/driver.py:699
msgid "Updating!"
msgstr ""

#: nova/virt/baremetal/driver.py:726 nova/virt/hyperv/hostops.py:141
#: nova/virt/libvirt/driver.py:3028 nova/virt/xenapi/host.py:149
msgid "Updating host stats"
msgstr ""

#: nova/virt/baremetal/nodes.py:42
#, python-format
msgid "Unknown baremetal driver %(d)s"
msgstr ""

#: nova/virt/baremetal/tilera.py:184
msgid "free_node...."
msgstr ""

#: nova/virt/baremetal/tilera.py:215
#, python-format
msgid "deactivate_node is called for node_id = %(id)s node_ip = %(ip)s"
msgstr ""

#: nova/virt/baremetal/tilera.py:220
msgid "status of node is set to 0"
msgstr ""

#: nova/virt/baremetal/tilera.py:231
msgid "rootfs is already removed"
msgstr ""

#: nova/virt/baremetal/tilera.py:263
msgid "Before ping to the bare-metal node"
msgstr ""

#: nova/virt/baremetal/tilera.py:274
#, python-format
msgid "TILERA_BOARD_#%(node_id)s %(node_ip)s is ready"
msgstr ""

#: nova/virt/baremetal/tilera.py:278
#, python-format
msgid "TILERA_BOARD_#%(node_id)s %(node_ip)s is not ready, out_msg=%(out_msg)s"
msgstr ""

#: nova/virt/baremetal/tilera.py:290
msgid "Noting to do for tilera nodes: vmlinux is in CF"
msgstr ""

#: nova/virt/baremetal/tilera.py:313
msgid "activate_node"
msgstr ""

#: nova/virt/baremetal/tilera.py:327
msgid "Node is unknown error state."
msgstr ""

#: nova/virt/disk/api.py:196
msgid "no capable image handler configured"
msgstr ""

#: nova/virt/disk/api.py:243
#, python-format
msgid "no disk image handler for: %s"
msgstr ""

#: nova/virt/disk/api.py:255
msgid "image already mounted"
msgstr ""

#: nova/virt/disk/api.py:321
#, python-format
msgid ""
"Failed to mount container filesystem '%(image)s' on '%(target)s': "
"%(errors)s"
msgstr ""

#: nova/virt/disk/api.py:338
#, python-format
msgid "Failed to unmount container filesystem: %s"
msgstr ""

#: nova/virt/disk/api.py:371
msgid "injected file path not valid"
msgstr ""

#: nova/virt/disk/api.py:516
msgid "Not implemented on Windows"
msgstr ""

#: nova/virt/disk/api.py:550
#, python-format
msgid "User %(username)s not found in password file."
msgstr ""

#: nova/virt/disk/api.py:566
#, python-format
msgid "User %(username)s not found in shadow file."
msgstr ""

#: nova/virt/disk/guestfs.py:41
#, python-format
msgid "unsupported partition: %s"
msgstr ""

#: nova/virt/disk/guestfs.py:66 nova/virt/disk/guestfs.py:80
#: nova/virt/disk/mount.py:132
#, python-format
msgid "Failed to mount filesystem: %s"
msgstr ""

#: nova/virt/disk/guestfs.py:79
msgid "unknown guestmount error"
msgstr ""

#: nova/virt/disk/guestfs.py:119
#, python-format
msgid "Failed to umount image at %s, guestmount was still running after 10s"
msgstr ""

#: nova/virt/disk/loop.py:31
#, python-format
msgid "Could not attach image to loopback: %s"
msgstr ""

#: nova/virt/disk/mount.py:83
#, python-format
msgid "partition search unsupported with %s"
msgstr ""

#: nova/virt/disk/mount.py:99
#, python-format
msgid "partition %s not found"
msgstr ""

#: nova/virt/disk/mount.py:100
#, python-format
msgid "Failed to map partitions: %s"
msgstr ""

#: nova/virt/disk/nbd.py:59
msgid "nbd unavailable: module not loaded"
msgstr ""

#: nova/virt/disk/nbd.py:64
msgid "No free nbd devices"
msgstr ""

#: nova/virt/disk/nbd.py:86
#, python-format
msgid "qemu-nbd error: %s"
msgstr ""

#: nova/virt/disk/nbd.py:98
#, python-format
msgid "nbd device %s did not show up"
msgstr ""

#: nova/virt/hyperv/driver.py:190 nova/virt/hyperv/driver.py:193
msgid "plug_vifs called"
msgstr ""

#: nova/virt/hyperv/driver.py:196
msgid "ensure_filtering_rules_for_instance called"
msgstr ""

#: nova/virt/hyperv/driver.py:201
msgid "unfilter_instance called"
msgstr ""

#: nova/virt/hyperv/driver.py:205
msgid "confirm_migration called"
msgstr ""

#: nova/virt/hyperv/driver.py:210
msgid "finish_revert_migration called"
msgstr ""

#: nova/virt/hyperv/driver.py:216
msgid "finish_migration called"
msgstr ""

#: nova/virt/hyperv/driver.py:219
msgid "get_console_output called"
msgstr ""

#: nova/virt/hyperv/hostops.py:112
#, python-format
msgid "Windows version: %s "
msgstr ""

#: nova/virt/hyperv/hostops.py:124
msgid "get_available_resource called"
msgstr ""

#: nova/virt/hyperv/hostops.py:161
msgid "get_host_stats called"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:52
msgid ""
"Live migration is not supported \"                     \"by this version "
"of Hyper-V"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:61
msgid "Live migration is not enabled on this host"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:64
msgid "Live migration networks are not configured on this host"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:68
msgid "live_migration called"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:94
#, python-format
msgid "Getting live migration networks for remote host: %s"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:113
#, python-format
msgid "Starting live migration for instance: %s"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:126
#, python-format
msgid "Failed to live migrate VM %s"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:129
#, python-format
msgid "Calling live migration recover_method for instance: %s"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:133
#, python-format
msgid "Calling live migration post_method for instance: %s"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:139
msgid "pre_live_migration called"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:157
msgid "post_live_migration_at_destination called"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:161
#, python-format
msgid "compare_cpu called %s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:57
#, python-format
msgid "Creating snapshot for instance %s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:71
#, python-format
msgid "Failed to create snapshot for VM %s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:83
#, python-format
msgid "Getting info for VHD %s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:106
#, python-format
msgid "Copying VHD %(src_vhd_path)s to %(dest_vhd_path)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:116
#, python-format
msgid "Copying base disk %(src_vhd_path)s to %(dest_base_disk_path)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:120
#, python-format
msgid ""
"Reconnecting copied base VHD %(dest_base_disk_path)s and diff VHD "
"%(dest_vhd_path)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:134
#, python-format
msgid ""
"Failed to reconnect base disk %(dest_base_disk_path)s and diff disk "
"%(dest_vhd_path)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:139
#, python-format
msgid "Merging base disk %(dest_base_disk_path)s and diff disk %(dest_vhd_path)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:151
#, python-format
msgid ""
"Failed to merge base disk %(dest_base_disk_path)s and diff disk "
"%(dest_vhd_path)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:164
#, python-format
msgid ""
"Updating Glance image %(image_id)s with content from merged disk "
"%(image_vhd_path)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:169
#, python-format
msgid "Snapshot image %(image_id)s updated for VM %(instance_name)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:172
#, python-format
msgid "Removing snapshot %s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:181
#, python-format
msgid "Failed to remove snapshot for VM %s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:186
#, python-format
msgid "Removing folder %s "
msgstr ""

#: nova/virt/hyperv/vmops.py:67
msgid "get_info called for instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:91
#, python-format
msgid "hyperv vm state: %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:97
#, python-format
msgid ""
"Got Info for vm %(instance_name)s: state=%(state)s, mem=%(memusage)s, "
"num_cpu=%(numprocs)s, uptime=%(uptime)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:133
#, python-format
msgid "cache image failed: %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:152
#, python-format
msgid "Starting VM %s "
msgstr ""

#: nova/virt/hyperv/vmops.py:154
#, python-format
msgid "Started VM %s "
msgstr ""

#: nova/virt/hyperv/vmops.py:156
#, python-format
msgid "spawn vm failed: %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:175
#, python-format
msgid "Failed to create VM %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:178
#, python-format
msgid "Created VM %s..."
msgstr ""

#: nova/virt/hyperv/vmops.py:195
#, python-format
msgid "Set memory for vm %s..."
msgstr ""

#: nova/virt/hyperv/vmops.py:208
#, python-format
msgid "Set vcpus for vm %s..."
msgstr ""

#: nova/virt/hyperv/vmops.py:212
#, python-format
msgid "Creating a scsi controller for %(vm_name)s for volume attaching"
msgstr ""

#: nova/virt/hyperv/vmops.py:221
msgid "Controller not found"
msgstr ""

#: nova/virt/hyperv/vmops.py:229
#, python-format
msgid "Failed to add scsi controller to VM %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:234
#, python-format
msgid "Creating disk for %(vm_name)s by attaching disk file %(vhdfile)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:261
#, python-format
msgid "Failed to add diskdrive to VM %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:264
#, python-format
msgid "New disk drive path is %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:283
#, python-format
msgid "Failed to add vhd file to VM %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:285
#, python-format
msgid "Created disk for %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:289
#, python-format
msgid "Creating nic for %s "
msgstr ""

#: nova/virt/hyperv/vmops.py:294
msgid "Cannot find vSwitch"
msgstr ""

#: nova/virt/hyperv/vmops.py:314
msgid "Failed creating a port on the external vswitch"
msgstr ""

#: nova/virt/hyperv/vmops.py:315
#, python-format
msgid "Failed creating port for %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:318
#, python-format
msgid "Created switch port %(vm_name)s on switch %(ext_path)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:330
#, python-format
msgid "Failed to add nic to VM %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:332
#, python-format
msgid "Created nic for %s "
msgstr ""

#: nova/virt/hyperv/vmops.py:339 nova/virt/hyperv/vmops.py:342
#, python-format
msgid "Attempting to bind NIC to %s "
msgstr ""

#: nova/virt/hyperv/vmops.py:347
msgid "No vSwitch specified, attaching to default"
msgstr ""

#: nova/virt/hyperv/vmops.py:372
#, python-format
msgid "Got request to destroy vm %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:416
#, python-format
msgid "Del: disk %(vhdfile)s vm %(instance_name)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:422
msgid "Pause instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:427
msgid "Unpause instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:433
msgid "Suspend instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:438
msgid "Resume instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:443
msgid "Power off instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:448
msgid "Power on instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:468
#, python-format
msgid "Successfully changed vm state of %(vm_name)s to %(req_state)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:497
#, python-format
msgid "use_cow_image:%s"
msgstr ""

#: nova/virt/hyperv/vmops.py:517
#, python-format
msgid "Failed to create Difference Disk from %(base)s to %(target)s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:54
#, python-format
msgid "duplicate name found: %s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:68
#, python-format
msgid ""
"WMI job failed: %(ErrorSummaryDescription)s - %(ErrorDescription)s - "
"%(ErrorCode)s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:73
#, python-format
msgid "WMI job succeeded: %(desc)s, Elapsed=%(elap)s "
msgstr ""

#: nova/virt/hyperv/vmutils.py:80 nova/virt/hyperv/vmutils.py:96
#, python-format
msgid "Creating folder %s "
msgstr ""

#: nova/virt/hyperv/vmutils.py:94
#, python-format
msgid "Removing existing folder %s "
msgstr ""

#: nova/virt/hyperv/volumeops.py:69 nova/virt/xenapi/vm_utils.py:483
#, python-format
msgid "block device info: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:97
#, python-format
msgid "Attach boot from volume failed: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:100
#, python-format
msgid "Unable to attach boot volume to instance %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:109 nova/virt/xenapi/volumeops.py:114
#, python-format
msgid "Attach_volume: %(connection_info)s, %(instance_name)s, %(mountpoint)s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:134
#, python-format
msgid "Attach volume failed: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:137 nova/virt/xenapi/volumeops.py:190
#, python-format
msgid "Unable to attach volume to instance %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:156
#, python-format
msgid "Failed to add volume to VM %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:170
#, python-format
msgid "Detach_volume: %(connection_info)s, %(instance_name)s, %(mountpoint)s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:187
#, python-format
msgid "Mounted disk to detach is: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:188
#, python-format
msgid "host_resource disk detached is: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:191
#, python-format
msgid "Physical disk detached is: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:198
#, python-format
msgid "Failed to remove volume from VM %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:207 nova/virt/libvirt/driver.py:603
msgid "Could not determine iscsi initiator name"
msgstr ""

#: nova/virt/hyperv/volumeops.py:224
#, python-format
msgid "device.InitiatorName: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:225
#, python-format
msgid "device.TargetName: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:226
#, python-format
msgid "device.ScsiPortNumber: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:227
#, python-format
msgid "device.ScsiPathId: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:228
#, python-format
msgid "device.ScsiTargetId): %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:229
#, python-format
msgid "device.ScsiLun: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:230
#, python-format
msgid "device.DeviceInterfaceGuid :%s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:232
#, python-format
msgid "device.DeviceInterfaceName: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:234
#, python-format
msgid "device.LegacyName: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:235
#, python-format
msgid "device.DeviceType: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:236
#, python-format
msgid "device.DeviceNumber %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:237
#, python-format
msgid "device.PartitionNumber :%s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:243 nova/virt/hyperv/volumeops.py:262
#, python-format
msgid "Unable to find a mounted disk for target_iqn: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:245
#, python-format
msgid "Device number : %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:246
#, python-format
msgid "Target lun : %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:252 nova/virt/hyperv/volumeops.py:259
#, python-format
msgid "Mounted disk is: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:276
#, python-format
msgid "Drive number to disconnect is: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:283
#, python-format
msgid "DeviceNumber : %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:288
#, python-format
msgid "Disk path to parse: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:290
#, python-format
msgid "start_device_id: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:292
#, python-format
msgid "end_device_id: %s"
msgstr ""

#: nova/virt/hyperv/volumeutils.py:51
#, python-format
msgid "An error has occurred when calling the iscsi initiator: %s"
msgstr ""

#: nova/virt/hyperv/volumeutils.py:68
msgid "The ISCSI initiator name can't be found. Choosing the default one"
msgstr ""

#: nova/virt/hyperv/volumeutils.py:121 nova/virt/libvirt/driver.py:1462
#: nova/virt/xenapi/vm_utils.py:476
#, python-format
msgid "block_device_list %s"
msgstr ""

#: nova/virt/libvirt/driver.py:332
#, python-format
msgid "Nova requires libvirt version %(major)i.%(minor)i.%(micro)i or greater."
msgstr ""

#: nova/virt/libvirt/driver.py:338
#, python-format
msgid "Connecting to libvirt: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:359
msgid "Connection to libvirt broke"
msgstr ""

#: nova/virt/libvirt/driver.py:381 nova/virt/libvirt/driver.py:384
#, python-format
msgid "Can not handle authentication request for %d credentials"
msgstr ""

#: nova/virt/libvirt/driver.py:466
#, python-format
msgid "Error from libvirt during destroy. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:480
msgid "During wait destroy, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:485
msgid "Instance destroyed successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:507
msgid "Error from libvirt during undefineFlags. Retrying with undefine"
msgstr ""

#: nova/virt/libvirt/driver.py:522
#, python-format
msgid "Error from libvirt during undefine. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:535
#, python-format
msgid "Error from libvirt during unfilter. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:552
#, python-format
msgid "Deleting instance files %(target)s"
msgstr ""

#: nova/virt/libvirt/driver.py:566
#, python-format
msgid "Failed to cleanup directory %(target)s: %(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:728
msgid "During detach_volume, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:738
msgid "attaching LXC block device"
msgstr ""

#: nova/virt/libvirt/driver.py:751
msgid "detaching LXC block device"
msgstr ""

#: nova/virt/libvirt/driver.py:883
msgid "Instance soft rebooted successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:887
msgid "Failed to soft reboot instance."
msgstr ""

#: nova/virt/libvirt/driver.py:919
msgid "Instance shutdown successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:954
msgid "Instance rebooted successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:1084
msgid "Instance is running"
msgstr ""

#: nova/virt/libvirt/driver.py:1091 nova/virt/powervm/operator.py:253
msgid "Instance spawned successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:1107
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr ""

#: nova/virt/libvirt/driver.py:1153
msgid "Guest does not have a console available"
msgstr ""

#: nova/virt/libvirt/driver.py:1197
#, python-format
msgid "Path '%(path)s' supports direct I/O"
msgstr ""

#: nova/virt/libvirt/driver.py:1201
#, python-format
msgid "Path '%(path)s' does not support direct I/O: '%(ex)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:1205 nova/virt/libvirt/driver.py:1209
#, python-format
msgid "Error on '%(path)s' while checking direct I/O: '%(ex)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:1275
msgid "Creating image"
msgstr ""

#: nova/virt/libvirt/driver.py:1401
msgid "Using config drive"
msgstr ""

#: nova/virt/libvirt/driver.py:1411
#, python-format
msgid "Creating config drive at %(path)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1425
#, python-format
msgid "Injecting %(injection)s into image %(img_id)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1435
#, python-format
msgid "Ignoring error injecting data into image %(img_id)s (%(e)s)"
msgstr ""

#: nova/virt/libvirt/driver.py:1509
#, python-format
msgid ""
"Config requested an explicit CPU model, but the current libvirt "
"hypervisor '%s' does not support selecting CPU models"
msgstr ""

#: nova/virt/libvirt/driver.py:1515
msgid "Config requested a custom CPU model, but no model name was provided"
msgstr ""

#: nova/virt/libvirt/driver.py:1519
msgid "A CPU model name should not be set when a host CPU model is requested"
msgstr ""

#: nova/virt/libvirt/driver.py:1523
#, python-format
msgid "CPU mode '%(mode)s' model '%(model)s' was chosen"
msgstr ""

#: nova/virt/libvirt/driver.py:1539
msgid ""
"Passthrough of the host CPU was requested but this libvirt version does "
"not support this feature"
msgstr ""

#: nova/virt/libvirt/driver.py:1831
msgid "Starting toXML method"
msgstr ""

#: nova/virt/libvirt/driver.py:1835
msgid "Finished toXML method"
msgstr ""

#: nova/virt/libvirt/driver.py:1852
#, python-format
msgid ""
"Error from libvirt while looking up %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:2104
msgid "libvirt version is too old (does not support getVersion)"
msgstr ""

#: nova/virt/libvirt/driver.py:2291
msgid "Block migration can not be used with shared storage."
msgstr ""

#: nova/virt/libvirt/driver.py:2299
msgid "Live migration can not be used without shared storage."
msgstr ""

#: nova/virt/libvirt/driver.py:2334
#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s: Disk of instance is too "
"large(available on destination host:%(available)s < need:%(necessary)s)"
msgstr ""

#: nova/virt/libvirt/driver.py:2354
#, python-format
msgid ""
"Instance launched has CPU info:\n"
"%s"
msgstr ""

#: nova/virt/libvirt/driver.py:2366
#, python-format
msgid ""
"CPU doesn't have compatibility.\n"
"\n"
"%(ret)s\n"
"\n"
"Refer to %(u)s"
msgstr ""

#: nova/virt/libvirt/driver.py:2383
#, python-format
msgid ""
"Creating tmpfile %s to notify to other compute nodes that they should "
"mount the same storage."
msgstr ""

#: nova/virt/libvirt/driver.py:2431
#, python-format
msgid "The firewall filter for %s does not exist"
msgstr ""

#: nova/virt/libvirt/driver.py:2501
#, python-format
msgid "Live Migration failure: %(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:2545
#, python-format
msgid "plug_vifs() failed %(cnt)d.Retry up to %(max_retry)d for %(hostname)s."
msgstr ""

#: nova/virt/libvirt/driver.py:2672
#, python-format
msgid "skipping %(path)s since it looks like volume"
msgstr ""

#: nova/virt/libvirt/driver.py:2721
#, python-format
msgid "Getting disk size of %(i_name)s: %(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:2783
msgid "Starting migrate_disk_and_power_off"
msgstr ""

#: nova/virt/libvirt/driver.py:2842
msgid "Instance running successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2849
msgid "Starting finish_migration"
msgstr ""

#: nova/virt/libvirt/driver.py:2900
msgid "Starting finish_revert_migration"
msgstr ""

#: nova/virt/libvirt/firewall.py:34
msgid ""
"Libvirt module could not be loaded. NWFilterFirewall will not work "
"correctly."
msgstr ""

#: nova/virt/libvirt/firewall.py:102
msgid "Called setup_basic_filtering in nwfilter"
msgstr ""

#: nova/virt/libvirt/firewall.py:110
msgid "Ensuring static filters"
msgstr ""

#: nova/virt/libvirt/firewall.py:191
#, python-format
msgid "The nwfilter(%(instance_filter_name)s) is not found."
msgstr ""

#: nova/virt/libvirt/firewall.py:214
#, python-format
msgid "The nwfilter(%(instance_filter_name)s) for%(name)s is not found."
msgstr ""

#: nova/virt/libvirt/firewall.py:230
msgid "iptables firewall: Setup Basic Filtering"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:213
msgid "You should specify libvirt_images_volume_group flag to use LVM images."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:276
#, python-format
msgid "Unknown image_type=%s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:164
#, python-format
msgid "%s is a valid instance name"
msgstr ""

#: nova/virt/libvirt/imagecache.py:167
#, python-format
msgid "%s has a disk file"
msgstr ""

#: nova/virt/libvirt/imagecache.py:169
#, python-format
msgid "Instance %(instance)s is backed by %(backing)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:182
#, python-format
msgid ""
"Instance %(instance)s is using a backing file %(backing)s which does not "
"appear in the image service"
msgstr ""

#: nova/virt/libvirt/imagecache.py:234
#, python-format
msgid "%(id)s (%(base_file)s): image verification failed"
msgstr ""

#: nova/virt/libvirt/imagecache.py:244
#, python-format
msgid "%(id)s (%(base_file)s): image verification skipped, no hash stored"
msgstr ""

#: nova/virt/libvirt/imagecache.py:263
#, python-format
msgid "Cannot remove %(base_file)s, it does not exist"
msgstr ""

#: nova/virt/libvirt/imagecache.py:275
#, python-format
msgid "Base file too young to remove: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:278
#, python-format
msgid "Removing base file: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:285
#, python-format
msgid "Failed to remove %(base_file)s, error was %(error)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:296
#, python-format
msgid "%(id)s (%(base_file)s): checking"
msgstr ""

#: nova/virt/libvirt/imagecache.py:315
#, python-format
msgid ""
"%(id)s (%(base_file)s): in use: on this node %(local)d local, %(remote)d "
"on other nodes"
msgstr ""

#: nova/virt/libvirt/imagecache.py:327
#, python-format
msgid ""
"%(id)s (%(base_file)s): warning -- an absent base file is in use! "
"instances: %(instance_list)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:335
#, python-format
msgid "%(id)s (%(base_file)s): in use on (%(remote)d on other nodes)"
msgstr ""

#: nova/virt/libvirt/imagecache.py:345
#, python-format
msgid "%(id)s (%(base_file)s): image is not in use"
msgstr ""

#: nova/virt/libvirt/imagecache.py:351
#, python-format
msgid "%(id)s (%(base_file)s): image is in use"
msgstr ""

#: nova/virt/libvirt/imagecache.py:374
#, python-format
msgid "Skipping verification, no base directory at %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:378
msgid "Verify base images"
msgstr ""

#: nova/virt/libvirt/imagecache.py:385
#, python-format
msgid "Image id %(id)s yields fingerprint %(fingerprint)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:403
#, python-format
msgid "Unknown base file: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:408
#, python-format
msgid "Active base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:411
#, python-format
msgid "Corrupt base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:415
#, python-format
msgid "Removable base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:423
msgid "Verification complete"
msgstr ""

#: nova/virt/libvirt/snapshots.py:83 nova/virt/libvirt/snapshots.py:86
#: nova/virt/libvirt/snapshots.py:89
msgid "LVM snapshots not implemented"
msgstr ""

#: nova/virt/libvirt/utils.py:131
#, python-format
msgid ""
"Insufficient Space on Volume Group %(vg)s. Only %(free_space)db "
"available, but %(size)db required by volume %(lv)s."
msgstr ""

#: nova/virt/libvirt/utils.py:140
#, python-format
msgid ""
"Volume group %(vg)s will not be able to hold sparse volume %(lv)s. "
"Virtual volume size is %(size)db, but free space on volume group is only "
"%(free_space)db."
msgstr ""

#: nova/virt/libvirt/utils.py:187
#, python-format
msgid "Path %s must be LVM logical volume"
msgstr ""

#: nova/virt/libvirt/utils.py:406
msgid "Can't retrieve root device path from instance libvirt configuration"
msgstr ""

#: nova/virt/libvirt/utils.py:495
#, python-format
msgid "Reading image info file: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:499
#, python-format
msgid "Read: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:505
#, python-format
msgid "Error reading image info file %(filename)s: %(error)s"
msgstr ""

#: nova/virt/libvirt/utils.py:529
#, python-format
msgid "Writing image info file: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:530
#, python-format
msgid "Wrote: %s"
msgstr ""

#: nova/virt/libvirt/vif.py:95
#, python-format
msgid "Ensuring vlan %(vlan)s and bridge %(bridge)s"
msgstr ""

#: nova/virt/libvirt/vif.py:105
#, python-format
msgid "Ensuring bridge %s"
msgstr ""

#: nova/virt/libvirt/vif.py:181 nova/virt/libvirt/vif.py:247
#: nova/virt/libvirt/vif.py:307
msgid "Failed while unplugging vif"
msgstr ""

#: nova/virt/libvirt/volume.py:174
#, python-format
msgid "iSCSI device not found at %s"
msgstr ""

#: nova/virt/libvirt/volume.py:177
#, python-format
msgid ""
"ISCSI volume not yet found at: %(mount_device)s. Will rescan & retry.  "
"Try number: %(tries)s"
msgstr ""

#: nova/virt/libvirt/volume.py:189
#, python-format
msgid "Found iSCSI node %(mount_device)s (after %(tries)s rescans)"
msgstr ""

#: nova/virt/libvirt/volume_nfs.py:81
#, python-format
msgid "%s is already mounted"
msgstr ""

#: nova/virt/powervm/common.py:54
msgid "Connection error connecting PowerVM manager"
msgstr ""

#: nova/virt/powervm/common.py:111
msgid "File transfer to PowerVM manager failed"
msgstr ""

#: nova/virt/powervm/exception.py:21
msgid "Connection to PowerVM manager failed"
msgstr ""

#: nova/virt/powervm/exception.py:25
msgid "File '%(file_path)' transfer to PowerVM manager failed"
msgstr ""

#: nova/virt/powervm/exception.py:29
#, python-format
msgid "LPAR instance '%(instance_name)s' could not be found"
msgstr ""

#: nova/virt/powervm/exception.py:33
#, python-format
msgid "LPAR instance '%(instance_name)s' creation failed"
msgstr ""

#: nova/virt/powervm/exception.py:37
msgid "No space left on any volume group"
msgstr ""

#: nova/virt/powervm/exception.py:45
#, python-format
msgid "Operation '%(operation)s' on LPAR '%(instance_name)s' timed out"
msgstr ""

#: nova/virt/powervm/exception.py:50
msgid "Image creation failed on PowerVM"
msgstr ""

#: nova/virt/powervm/exception.py:54
#, python-format
msgid ""
"Insufficient free memory on PowerVM system to spawn instance "
"'%(instance_name)s'"
msgstr ""

#: nova/virt/powervm/exception.py:59
#, python-format
msgid ""
"Insufficient available CPUs on PowerVM system to spawn instance "
"'%(instance_name)s'"
msgstr ""

#: nova/virt/powervm/exception.py:64
#, python-format
msgid "PowerVM LPAR instance '%(instance_name)s' cleanup failed"
msgstr ""

#: nova/virt/powervm/operator.py:91
#, python-format
msgid "LPAR instance '%s' not found"
msgstr ""

#: nova/virt/powervm/operator.py:174
msgid "Not enough free memory in the host"
msgstr ""

#: nova/virt/powervm/operator.py:184
msgid "Insufficient available CPU on PowerVM"
msgstr ""

#: nova/virt/powervm/operator.py:208
#, python-format
msgid "Creating LPAR instance '%s'"
msgstr ""

#: nova/virt/powervm/operator.py:211
#, python-format
msgid "LPAR instance '%s' creation failed"
msgstr ""

#: nova/virt/powervm/operator.py:221
#, python-format
msgid "Fetching image '%s' from glance"
msgstr ""

#: nova/virt/powervm/operator.py:225
#, python-format
msgid "Copying image '%s' to IVM"
msgstr ""

#: nova/virt/powervm/operator.py:230
msgid "Creating logical volume"
msgstr ""

#: nova/virt/powervm/operator.py:235
#, python-format
msgid "Copying image to the device '%s'"
msgstr ""

#: nova/virt/powervm/operator.py:238
#, python-format
msgid "PowerVM image creation failed: %s"
msgstr ""

#: nova/virt/powervm/operator.py:244
#, python-format
msgid "Activating the LPAR instance '%s'"
msgstr ""

#: nova/virt/powervm/operator.py:258
#, python-format
msgid "Instance '%s' failed to boot"
msgstr ""

#: nova/virt/powervm/operator.py:275
#, python-format
msgid "During destroy, LPAR instance '%s' was not found on PowerVM system."
msgstr ""

#: nova/virt/powervm/operator.py:284
#, python-format
msgid "Shutting down the instance '%s'"
msgstr ""

#: nova/virt/powervm/operator.py:288
#, python-format
msgid "Removing the logical volume '%s'"
msgstr ""

#: nova/virt/powervm/operator.py:291
#, python-format
msgid "Deleting the LPAR instance '%s'"
msgstr ""

#: nova/virt/powervm/operator.py:294
msgid "PowerVM instance cleanup failed"
msgstr ""

#: nova/virt/powervm/operator.py:495
msgid "Could not create logical volume. No space left on any volume group."
msgstr ""

#: nova/virt/powervm/operator.py:554
msgid "Unable to get checksum"
msgstr ""

#: nova/virt/powervm/operator.py:557
msgid "Image checksums do not match"
msgstr ""

#: nova/virt/powervm/operator.py:582
msgid "Uncompressed image file not found"
msgstr ""

#: nova/virt/vmwareapi/driver.py:111
msgid ""
"Must specify vmwareapi_host_ip,vmwareapi_host_username and "
"vmwareapi_host_password to usecompute_driver=vmwareapi.VMWareESXDriver"
msgstr ""

#: nova/virt/vmwareapi/driver.py:275
#, python-format
msgid "In vmwareapi:_create_session, got this exception: %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:358
#, python-format
msgid "In vmwareapi:_call_method, got this exception: %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:393
#, python-format
msgid "Task [%(task_name)s] %(task_ref)s status: success"
msgstr ""

#: nova/virt/vmwareapi/driver.py:398
#, python-format
msgid "Task [%(task_name)s] %(task_ref)s status: error %(error_info)s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:402
#, python-format
msgid "In vmwareapi:_poll_task, Got this error %s"
msgstr ""

#: nova/virt/vmwareapi/error_util.py:93
#, python-format
msgid "Error(s) %s occurred in the call to RetrieveProperties"
msgstr ""

#: nova/virt/vmwareapi/fake.py:44 nova/virt/xenapi/fake.py:77
#, python-format
msgid "%(text)s: _db_content => %(content)s"
msgstr ""

#: nova/virt/vmwareapi/fake.py:131
#, python-format
msgid "Property %(attr)s not set for the managed object %(name)s"
msgstr ""

#: nova/virt/vmwareapi/fake.py:436
msgid "There is no VM registered"
msgstr ""

#: nova/virt/vmwareapi/fake.py:438 nova/virt/vmwareapi/fake.py:608
#, python-format
msgid "Virtual Machine with ref %s is not there"
msgstr ""

#: nova/virt/vmwareapi/fake.py:501
#, python-format
msgid "Logging out a session that is invalid or already logged out: %s"
msgstr ""

#: nova/virt/vmwareapi/fake.py:516
msgid "Session is faulty"
msgstr ""

#: nova/virt/vmwareapi/fake.py:519
msgid "Session Invalid"
msgstr ""

#: nova/virt/vmwareapi/fake.py:605
msgid " No Virtual Machine has been registered yet"
msgstr ""

#: nova/virt/vmwareapi/io_util.py:103
#, python-format
msgid "Glance image %s is in killed state"
msgstr ""

#: nova/virt/vmwareapi/io_util.py:111
#, python-format
msgid "Glance image %(image_id)s is in unknown state - %(state)s"
msgstr ""

#: nova/virt/vmwareapi/network_utils.py:128
msgid ""
"ESX SOAP server returned an empty port group for the host system in its "
"response"
msgstr ""

#: nova/virt/vmwareapi/network_utils.py:155
#, python-format
msgid "Creating Port Group with name %s on the ESX host"
msgstr ""

#: nova/virt/vmwareapi/network_utils.py:169
#, python-format
msgid "Created Port Group with name %s on the ESX host"
msgstr ""

#: nova/virt/vmwareapi/read_write_util.py:145
#, python-format
msgid "Exception during HTTP connection close in VMWareHTTpWrite. Exception is %s"
msgstr ""

#: nova/virt/vmwareapi/vim.py:84
msgid "Unable to import suds."
msgstr ""

#: nova/virt/vmwareapi/vim.py:90
msgid "Must specify vmwareapi_wsdl_loc"
msgstr ""

#: nova/virt/vmwareapi/vim.py:145
#, python-format
msgid "No such SOAP method '%s' provided by VI SDK"
msgstr ""

#: nova/virt/vmwareapi/vim.py:150
#, python-format
msgid "httplib error in %s: "
msgstr ""

#: nova/virt/vmwareapi/vim.py:157
#, python-format
msgid "Socket error in %s: "
msgstr ""

#: nova/virt/vmwareapi/vim.py:162
#, python-format
msgid "Type error in  %s: "
msgstr ""

#: nova/virt/vmwareapi/vim.py:166
#, python-format
msgid "Exception in %s "
msgstr ""

#: nova/virt/vmwareapi/vmops.py:66
msgid "Getting list of instances"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:82
#, python-format
msgid "Got total of %s instances"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:126
msgid "Couldn't get a local Datastore reference"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:196
msgid "Creating VM on the ESX  host"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:204
msgid "Created VM on the ESX  host"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:232
#, python-format
msgid ""
"Creating Virtual Disk of size  %(vmdk_file_size_in_kb)s KB and adapter "
"type  %(adapter_type)s on the ESX host local store %(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:250
#, python-format
msgid ""
"Created Virtual Disk of size %(vmdk_file_size_in_kb)s KB on the ESX host "
"local store %(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:260
#, python-format
msgid ""
"Deleting the file %(flat_uploaded_vmdk_path)s on the ESX host localstore "
"%(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:273
#, python-format
msgid ""
"Deleted the file %(flat_uploaded_vmdk_path)s on the ESX host local store "
"%(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:285
#, python-format
msgid ""
"Downloading image file data %(image_ref)s to the ESX data store "
"%(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:301
#, python-format
msgid ""
"Downloaded image file data %(image_ref)s to the ESX data store "
"%(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:319
msgid "Reconfiguring VM instance to attach the image disk"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:326
msgid "Reconfigured VM instance to attach the image disk"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:333
msgid "Powering on the VM instance"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:339
msgid "Powered on the VM instance"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:385
msgid "Creating Snapshot of the VM instance"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:395
msgid "Created Snapshot of the VM instance"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:438
msgid "Copying disk data before snapshot of the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:451
msgid "Copied disk data before snapshot of the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:460
#, python-format
msgid "Uploading image %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:474
#, python-format
msgid "Uploaded image %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:485
#, python-format
msgid "Deleting temporary vmdk file %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:494
#, python-format
msgid "Deleted temporary vmdk file %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:526
msgid "instance is not powered on"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:533
msgid "Rebooting guest OS of VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:536
msgid "Rebooted guest OS of VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:538
msgid "Doing hard reboot of VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:542
msgid "Did hard reboot of VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:554
msgid "instance not present"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:573
msgid "Powering off the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:578
msgid "Powered off the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:582
msgid "Unregistering the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:585
msgid "Unregistered the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:587
#, python-format
msgid ""
"In vmwareapi:vmops:destroy, got this exception while un-registering the "
"VM: %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:599
#, python-format
msgid "Deleting contents of the VM from datastore %(datastore_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:609
#, python-format
msgid "Deleted contents of the VM from datastore %(datastore_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:614
#, python-format
msgid ""
"In vmwareapi:vmops:destroy, got this exception while deleting the VM "
"contents from the disk: %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:623
msgid "pause not supported for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:627
msgid "unpause not supported for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:641
msgid "Suspending the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:645
msgid "Suspended the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:648
msgid "instance is powered off and can not be suspended."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:651
msgid "VM was already in suspended state. So returning without doing anything"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:664
msgid "Resuming the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:669
msgid "Resumed the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:671
msgid "instance is not in a suspended state"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:707
msgid "get_diagnostics not implemented for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:765
#, python-format
msgid "Reconfiguring VM instance to set the machine id with ip - %(ip_addr)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:773
#, python-format
msgid "Reconfigured VM instance to set the machine id with ip - %(ip_addr)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:810
#, python-format
msgid "Creating directory with path %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:814
#, python-format
msgid "Created directory with path %s"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:91
#, python-format
msgid "Downloading image %s from glance image server"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:108
#, python-format
msgid "Downloaded image %s from glance image server"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:114
#, python-format
msgid "Uploading image %s to the Glance image server"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:137
#, python-format
msgid "Uploaded image %s to the Glance image server"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:148
#, python-format
msgid "Getting image size for the image %s"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:153
#, python-format
msgid "Got image size of %(size)s for the image %(image)s"
msgstr ""

#: nova/virt/xenapi/agent.py:80 nova/virt/xenapi/vmops.py:1471
#, python-format
msgid "TIMEOUT: The call to %(method)s timed out. args=%(args)r"
msgstr ""

#: nova/virt/xenapi/agent.py:84 nova/virt/xenapi/vmops.py:1475
#, python-format
msgid ""
"NOT IMPLEMENTED: The call to %(method)s is not supported by the agent. "
"args=%(args)r"
msgstr ""

#: nova/virt/xenapi/agent.py:89 nova/virt/xenapi/vmops.py:1480
#, python-format
msgid "The call to %(method)s returned an error: %(e)s. args=%(args)r"
msgstr ""

#: nova/virt/xenapi/agent.py:99
#, python-format
msgid ""
"The agent call to %(method)s returned an invalid response: %(ret)r. "
"path=%(path)s; args=%(args)r"
msgstr ""

#: nova/virt/xenapi/agent.py:109
#, python-format
msgid "Failed to query agent version: %(resp)r"
msgstr ""

#: nova/virt/xenapi/agent.py:127
msgid "Querying agent version"
msgstr ""

#: nova/virt/xenapi/agent.py:141
msgid "Reached maximum time attempting to query agent version"
msgstr ""

#: nova/virt/xenapi/agent.py:149
#, python-format
msgid "Updating agent to %s"
msgstr ""

#: nova/virt/xenapi/agent.py:157
#, python-format
msgid "Failed to update agent: %(resp)r"
msgstr ""

#: nova/virt/xenapi/agent.py:171
msgid "Setting admin password"
msgstr ""

#: nova/virt/xenapi/agent.py:182
#, python-format
msgid "Failed to exchange keys: %(resp)r"
msgstr ""

#: nova/virt/xenapi/agent.py:202
#, python-format
msgid "Failed to update password: %(resp)r"
msgstr ""

#: nova/virt/xenapi/agent.py:209
#, python-format
msgid "Injecting file path: %r"
msgstr ""

#: nova/virt/xenapi/agent.py:222
#, python-format
msgid "Failed to inject file: %(resp)r"
msgstr ""

#: nova/virt/xenapi/agent.py:229
msgid "Resetting network"
msgstr ""

#: nova/virt/xenapi/agent.py:235
#, python-format
msgid "Failed to reset network: %(resp)r"
msgstr ""

#: nova/virt/xenapi/agent.py:255
msgid ""
"XenServer tools installed in this image are capable of network injection."
"  Networking files will not bemanipulated"
msgstr ""

#: nova/virt/xenapi/agent.py:263
msgid ""
"XenServer tools are present in this image but are not capable of network "
"injection"
msgstr ""

#: nova/virt/xenapi/agent.py:267
msgid "XenServer tools are not installed in this image"
msgstr ""

#: nova/virt/xenapi/agent.py:319
#, python-format
msgid "OpenSSL error: %s"
msgstr ""

#: nova/virt/xenapi/driver.py:135
msgid ""
"Must specify xenapi_connection_url, xenapi_connection_username "
"(optionally), and xenapi_connection_password to use "
"compute_driver=xenapi.XenAPIDriver"
msgstr ""

#: nova/virt/xenapi/driver.py:162
msgid "Failure while cleaning up attached VDIs"
msgstr ""

#: nova/virt/xenapi/driver.py:363
#, python-format
msgid "Could not determine key: %s"
msgstr ""

#: nova/virt/xenapi/driver.py:574
msgid "Host startup on XenServer is not supported."
msgstr ""

#: nova/virt/xenapi/driver.py:626
msgid "Unable to log in to XenAPI (is the Dom0 disk full?)"
msgstr ""

#: nova/virt/xenapi/driver.py:664
msgid "Host is member of a pool, but DB says otherwise"
msgstr ""

#: nova/virt/xenapi/driver.py:748 nova/virt/xenapi/driver.py:762
#, python-format
msgid "Got exception: %s"
msgstr ""

#: nova/virt/xenapi/fake.py:670 nova/virt/xenapi/fake.py:772
#: nova/virt/xenapi/fake.py:791 nova/virt/xenapi/fake.py:859
msgid "Raising NotImplemented"
msgstr ""

#: nova/virt/xenapi/fake.py:672
#, python-format
msgid "xenapi.fake does not have an implementation for %s"
msgstr ""

#: nova/virt/xenapi/fake.py:706
#, python-format
msgid "Calling %(localname)s %(impl)s"
msgstr ""

#: nova/virt/xenapi/fake.py:711
#, python-format
msgid "Calling getter %s"
msgstr ""

#: nova/virt/xenapi/fake.py:714
#, python-format
msgid "Calling setter %s"
msgstr ""

#: nova/virt/xenapi/fake.py:774
#, python-format
msgid ""
"xenapi.fake does not have an implementation for %s or it has been called "
"with the wrong number of arguments"
msgstr ""

#: nova/virt/xenapi/host.py:71
#, python-format
msgid ""
"Instance %(name)s running on %(host)s could not be found in the database:"
" assuming it is a worker VM and skip ping migration to a new host"
msgstr ""

#: nova/virt/xenapi/host.py:157
#, python-format
msgid "Unable to get SR for this host: %s"
msgstr ""

#: nova/virt/xenapi/host.py:191
#, python-format
msgid "Failed to extract instance support from %s"
msgstr ""

#: nova/virt/xenapi/host.py:208
msgid "Unable to get updated status"
msgstr ""

#: nova/virt/xenapi/host.py:211
#, python-format
msgid "The call to %(method)s returned an error: %(e)s."
msgstr ""

#: nova/virt/xenapi/network_utils.py:29
#, python-format
msgid "Found non-unique network for name_label %s"
msgstr ""

#: nova/virt/xenapi/network_utils.py:47
#, python-format
msgid "Found non-unique network for bridge %s"
msgstr ""

#: nova/virt/xenapi/network_utils.py:49
#, python-format
msgid "Found no network for bridge %s"
msgstr ""

#: nova/virt/xenapi/pool.py:75
#, python-format
msgid ""
"Aggregate %(aggregate_id)s: unrecoverable state during operation on "
"%(host)s"
msgstr ""

#: nova/virt/xenapi/pool.py:166
#, python-format
msgid "Unable to eject %(host)s from the pool; pool not empty"
msgstr ""

#: nova/virt/xenapi/pool.py:182
#, python-format
msgid "Unable to eject %(host)s from the pool; No master found"
msgstr ""

#: nova/virt/xenapi/pool.py:199
#, python-format
msgid "Pool-Join failed: %(e)s"
msgstr ""

#: nova/virt/xenapi/pool.py:202
#, python-format
msgid "Unable to join %(host)s in the pool"
msgstr ""

#: nova/virt/xenapi/pool.py:218
#, python-format
msgid "Pool-eject failed: %(e)s"
msgstr ""

#: nova/virt/xenapi/pool.py:230
#, python-format
msgid "Unable to set up pool: %(e)s."
msgstr ""

#: nova/virt/xenapi/pool.py:241
#, python-format
msgid "Pool-set_name_label failed: %(e)s"
msgstr ""

#: nova/virt/xenapi/vif.py:104
#, python-format
msgid "Found no PIF for device %s"
msgstr ""

#: nova/virt/xenapi/vif.py:123
#, python-format
msgid ""
"PIF %(pif_rec['uuid'])s for network %(bridge)s has VLAN id %(pif_vlan)d. "
"Expected %(vlan_num)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:257
msgid "Created VM"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:269
msgid "VM destroyed"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:276
msgid "VM already halted, skipping shutdown..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:280
msgid "Shutting down VM"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:312
#, python-format
msgid "VBD not found in instance %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:329
#, python-format
msgid "VBD %s already detached"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:332
#, python-format
msgid "VBD %(vbd_ref)s detach rejected, attempt %(num_attempt)d/%(max_attempts)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:337
#, python-format
msgid "Unable to unplug VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:342
#, python-format
msgid "Reached maximum number of retries trying to unplug VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:353
#, python-format
msgid "Unable to destroy VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:372
#, python-format
msgid "Creating %(vbd_type)s-type VBD for VM %(vm_ref)s, VDI %(vdi_ref)s ... "
msgstr ""

#: nova/virt/xenapi/vm_utils.py:375
#, python-format
msgid "Created VBD %(vbd_ref)s for VM %(vm_ref)s, VDI %(vdi_ref)s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:391
#, python-format
msgid "Unable to destroy VDI %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:423
#, python-format
msgid ""
"Created VDI %(vdi_ref)s (%(name_label)s, %(virtual_size)s, %(read_only)s)"
" on %(sr_ref)s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:454
msgid "SR not present and could not be introduced"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:555
#, python-format
msgid "Cloned VDI %(vdi_ref)s from VDI %(vdi_to_clone_ref)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:575
#, python-format
msgid "No primary VDI found for %(vm_ref)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:584
msgid "Starting snapshot for VM"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:632
#, python-format
msgid "Destroying cached VDI '%(vdi_uuid)s'"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:690
#, python-format
msgid "Asking xapi to upload %(vdi_uuids)s as ID %(image_id)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:876
#, python-format
msgid ""
"Fast cloning is only supported on default local SR of type ext. SR on "
"this system was found to be of type %(sr_type)s. Ignoring the cow flag."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:934
#, python-format
msgid "Unrecognized cache_images value '%s', defaulting to True"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:968
#, python-format
msgid "Fetched VDIs of type '%(vdi_type)s' with UUID '%(vdi_uuid)s'"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:980
#, python-format
msgid ""
"download_vhd %(image_id)s, attempt %(attempt_num)d/%(max_attempts)d, "
"params: %(params)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:993
#, python-format
msgid "download_vhd failed: %r"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1029
#, python-format
msgid "Invalid value '%s' for xenapi_torrent_images"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1040
#, python-format
msgid "Asking xapi to fetch vhd image %(image_id)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1104
#, python-format
msgid "vdi_uuid=%(cur_vdi_uuid)s vdi_size_bytes=%(vdi_size_bytes)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1120
#, python-format
msgid "image_size_bytes=%(size_bytes)d, allowed_size_bytes=%(allowed_size_bytes)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1124
#, python-format
msgid ""
"Image size %(size_bytes)d exceeded instance_type allowed size "
"%(allowed_size_bytes)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1146
#, python-format
msgid "Fetching image %(image_id)s, type %(image_type_str)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1159
#, python-format
msgid "Size for image %(image_id)s: %(virtual_size)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1168
#, python-format
msgid ""
"Kernel/Ramdisk image is too large: %(vdi_size)d bytes, max %(max_size)d "
"bytes"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1187
#, python-format
msgid "Copying VDI %s to /boot/guest on dom0"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1201
#, python-format
msgid "Kernel/Ramdisk VDI %s destroyed"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1210
msgid "Failed to fetch glance image"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1248
#, python-format
msgid "Detected %(image_type_str)s format for image %(image_ref)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1269
#, python-format
msgid "Looking up vdi %s for PV kernel"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1287
#, python-format
msgid "Unknown image format %(disk_image_type)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1318
#, python-format
msgid "VDI %s is still available"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1414
#, python-format
msgid "Unable to parse rrd of %(vm_uuid)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1441
#, python-format
msgid "Re-scanning SR %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1469
#, python-format
msgid "Flag sr_matching_filter '%s' does not respect formatting convention"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1487
msgid ""
"XenAPI is unable to find a Storage Repository to install guest instances "
"on. Please check your configuration and/or configure the flag "
"'sr_matching_filter'"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1500
msgid "Cannot find SR of content-type ISO"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1508
#, python-format
msgid "ISO: looking at SR %(sr_rec)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1510
msgid "ISO: not iso content"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1513
msgid "ISO: iso content_type, no 'i18n-key' key"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1516
msgid "ISO: iso content_type, i18n-key value not 'local-storage-iso'"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1520
msgid "ISO: SR MATCHing our criteria"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1522
msgid "ISO: ISO, looking to see if it is host local"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1525
#, python-format
msgid "ISO: PBD %(pbd_ref)s disappeared"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1528
#, python-format
msgid "ISO: PBD matching, want %(pbd_rec)s, have %(host)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1531
msgid "ISO: SR with local PBD"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1553
#, python-format
msgid ""
"Unable to obtain RRD XML for VM %(vm_uuid)s with server details: "
"%(server)s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1569
#, python-format
msgid "Unable to obtain RRD XML updates with server details: %(server)s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1623
#, python-format
msgid "Invalid statistics data from Xenserver: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1683
#, python-format
msgid "VHD %(vdi_uuid)s has parent %(parent_uuid)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1770
#, python-format
msgid ""
"Parent %(parent_uuid)s doesn't match original parent "
"%(original_parent_uuid)s, waiting for coalesce..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1780
#, python-format
msgid "VHD coalesce attempts exceeded (%(max_attempts)d), giving up..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1815
#, python-format
msgid "Timeout waiting for device %s to be created"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1835
#, python-format
msgid "Disconnecting stale VDI %s from compute domU"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1848
#, python-format
msgid "Plugging VBD %s ... "
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1851
#, python-format
msgid "Plugging VBD %s done."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1853
#, python-format
msgid "VBD %(vbd_ref)s plugged as %(orig_dev)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1856
#, python-format
msgid "VBD %(vbd_ref)s plugged into wrong dev, remapping to %(dev)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1861
#, python-format
msgid "Destroying VBD for VDI %s ... "
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1869
#, python-format
msgid "Destroying VBD for VDI %s done."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1882
#, python-format
msgid "Running pygrub against %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1889
#, python-format
msgid "Found Xen kernel %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1891
msgid "No Xen kernel found.  Booting HVM."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1904
msgid "Partitions:"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1910
#, python-format
msgid "  %(num)s: %(ptype)s %(size)d sectors"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1935
#, python-format
msgid ""
"Writing partition table %(primary_first)d %(primary_last)d to "
"%(dev_path)s..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1948
#, python-format
msgid "Writing partition table %s done."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2002
#, python-format
msgid ""
"Starting sparse_copy src=%(src_path)s dst=%(dst_path)s "
"virtual_size=%(virtual_size)d block_size=%(block_size)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2034
#, python-format
msgid ""
"Finished sparse_copy in %(duration).2f secs, %(compression_pct).2f%% "
"reduction in size"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2083
msgid "Manipulating interface files directly"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2092
#, python-format
msgid "Failed to mount filesystem (expected for non-linux instances): %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2204
msgid "This domU must be running on the host specified by xenapi_connection_url"
msgstr ""

#: nova/virt/xenapi/vmops.py:126 nova/virt/xenapi/vmops.py:664
#, python-format
msgid "Updating progress to %(progress)d"
msgstr ""

#: nova/virt/xenapi/vmops.py:229
msgid "Starting instance"
msgstr ""

#: nova/virt/xenapi/vmops.py:297
msgid "Removing kernel/ramdisk files from dom0"
msgstr ""

#: nova/virt/xenapi/vmops.py:369
#, python-format
msgid "Block device information present: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:400
msgid "Failed to spawn, rolling back"
msgstr ""

#: nova/virt/xenapi/vmops.py:473
msgid "Detected ISO image type, creating blank VM for install"
msgstr ""

#: nova/virt/xenapi/vmops.py:490
msgid "Auto configuring disk, attempting to resize partition..."
msgstr ""

#: nova/virt/xenapi/vmops.py:516
msgid "Starting VM"
msgstr ""

#: nova/virt/xenapi/vmops.py:523
#, python-format
msgid ""
"Latest agent build for %(hypervisor)s/%(os)s/%(architecture)s is "
"%(version)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:526
#, python-format
msgid "No agent build found for %(hypervisor)s/%(os)s/%(architecture)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:533
msgid "Waiting for instance state to become running"
msgstr ""

#: nova/virt/xenapi/vmops.py:548
#, python-format
msgid "Instance agent version: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:575
msgid "Setting VCPU weight"
msgstr ""

#: nova/virt/xenapi/vmops.py:583
#, python-format
msgid "Could not find VM with name %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:633
msgid "Finished snapshot and upload for VM"
msgstr ""

#: nova/virt/xenapi/vmops.py:637
#, python-format
msgid "Migrating VHD '%(vdi_uuid)s' with seq_num %(seq_num)d"
msgstr ""

#: nova/virt/xenapi/vmops.py:645
msgid "Failed to transfer vhd to new host"
msgstr ""

#: nova/virt/xenapi/vmops.py:682
#, python-format
msgid "Resizing down VDI %(vdi_uuid)s from %(old_gb)dGB to %(new_gb)dGB"
msgstr ""

#: nova/virt/xenapi/vmops.py:806
#, python-format
msgid "Resizing up VDI %(vdi_uuid)s from %(old_gb)dGB to %(new_gb)dGB"
msgstr ""

#: nova/virt/xenapi/vmops.py:811
msgid "Resize complete"
msgstr ""

#: nova/virt/xenapi/vmops.py:855
msgid "Starting halted instance found during reboot"
msgstr ""

#: nova/virt/xenapi/vmops.py:940
msgid "Unable to find root VBD/VDI for VM"
msgstr ""

#: nova/virt/xenapi/vmops.py:966
msgid "Destroying VDIs"
msgstr ""

#: nova/virt/xenapi/vmops.py:993
msgid "Using RAW or VHD, skipping kernel and ramdisk deletion"
msgstr ""

#: nova/virt/xenapi/vmops.py:1000
msgid "instance has a kernel or ramdisk but not both"
msgstr ""

#: nova/virt/xenapi/vmops.py:1007
msgid "kernel/ramdisk files removed"
msgstr ""

#: nova/virt/xenapi/vmops.py:1033
msgid "Destroying VM"
msgstr ""

#: nova/virt/xenapi/vmops.py:1059
msgid "VM is not present, skipping destroy..."
msgstr ""

#: nova/virt/xenapi/vmops.py:1110
#, python-format
msgid "Instance is already in Rescue Mode: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1144
msgid "VM is not present, skipping soft delete..."
msgstr ""

#: nova/virt/xenapi/vmops.py:1192
#, python-format
msgid "Found %(instance_count)d hung reboots older than %(timeout)d seconds"
msgstr ""

#: nova/virt/xenapi/vmops.py:1196
msgid "Automatically hard rebooting"
msgstr ""

#: nova/virt/xenapi/vmops.py:1295
msgid "Fetching VM ref while BUILDING failed"
msgstr ""

#: nova/virt/xenapi/vmops.py:1378
msgid "Injecting network info to xenstore"
msgstr ""

#: nova/virt/xenapi/vmops.py:1397
msgid "Creating vifs"
msgstr ""

#: nova/virt/xenapi/vmops.py:1406
#, python-format
msgid "Creating VIF for network %(network_ref)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1409
#, python-format
msgid "Created VIF %(vif_ref)s, network %(network_ref)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1434
msgid "Injecting hostname to xenstore"
msgstr ""

#: nova/virt/xenapi/vmops.py:1530
#, python-format
msgid ""
"Destination host:%(hostname)s must be in the same aggregate as the source"
" server"
msgstr ""

#: nova/virt/xenapi/vmops.py:1562
msgid "Migrate Receive failed"
msgstr ""

#: nova/virt/xenapi/vmops.py:1610
msgid "VM.assert_can_migratefailed"
msgstr ""

#: nova/virt/xenapi/vmops.py:1646
msgid "Migrate Send failed"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:41
msgid "creating sr within volume_utils"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:44 nova/virt/xenapi/volume_utils.py:72
#, python-format
msgid "type is = %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:47 nova/virt/xenapi/volume_utils.py:75
#, python-format
msgid "name = %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:60
#, python-format
msgid "Created %(label)s as %(sr_ref)s."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:65 nova/virt/xenapi/volume_utils.py:163
msgid "Unable to create Storage Repository"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:69
msgid "introducing sr within volume_utils"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:92 nova/virt/xenapi/volume_utils.py:159
#: nova/virt/xenapi/volumeops.py:150
#, python-format
msgid "Introduced %(label)s as %(sr_ref)s."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:95
msgid "Creating pbd for SR"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:97
msgid "Plugging SR"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:105 nova/virt/xenapi/volumeops.py:154
msgid "Unable to introduce Storage Repository"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:116 nova/virt/xenapi/volumeops.py:46
msgid "Unable to get SR using uuid"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:118
#, python-format
msgid "Forgetting SR %s..."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:126
msgid "Unable to forget Storage Repository"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:146
#, python-format
msgid "Introducing %s..."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:175
#, python-format
msgid "Unable to find SR from VBD %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:193
#, python-format
msgid "Ignoring exception %(exc)s when getting PBDs for %(sr_ref)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:199
#, python-format
msgid "Ignoring exception %(exc)s when unplugging PBD %(pbd)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:223
#, python-format
msgid "Unable to introduce VDI on SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:231
#, python-format
msgid "Unable to get record of VDI %s on"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:253
#, python-format
msgid "Unable to introduce VDI for SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:263
#, python-format
msgid "Error finding vdis in SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:270
#, python-format
msgid "Unable to find vbd for vdi %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:281
#, python-format
msgid "Unable to obtain target information %(mountpoint)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:309
#, python-format
msgid "Unable to obtain target information %(connection_data)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:335
#, python-format
msgid "Mountpoint cannot be translated: %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:62
msgid "Could not find VDI ref"
msgstr ""

#: nova/virt/xenapi/volumeops.py:67
#, python-format
msgid "Creating SR %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:70
msgid "Could not create SR"
msgstr ""

#: nova/virt/xenapi/volumeops.py:73
msgid "Could not retrieve SR record"
msgstr ""

#: nova/virt/xenapi/volumeops.py:78
#, python-format
msgid "Introducing SR %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:81
msgid "SR found in xapi database. No need to introduce"
msgstr ""

#: nova/virt/xenapi/volumeops.py:86
msgid "Could not introduce SR"
msgstr ""

#: nova/virt/xenapi/volumeops.py:90
#, python-format
msgid "Checking for SR %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:100
#, python-format
msgid "SR %s not found in the xapi database"
msgstr ""

#: nova/virt/xenapi/volumeops.py:106
msgid "Could not forget SR"
msgstr ""

#: nova/virt/xenapi/volumeops.py:172
#, python-format
msgid "Unable to create VDI on SR %(sr_ref)s for instance %(instance_name)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:182
#, python-format
msgid "Unable to use SR %(sr_ref)s for instance %(instance_name)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:193
#, python-format
msgid "Mountpoint %(mountpoint)s attached to instance %(instance_name)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:202
#, python-format
msgid "Detach_volume: %(instance_name)s, %(mountpoint)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:210
#, python-format
msgid "Unable to locate volume %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:219
#, python-format
msgid "Unable to detach volume %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:224
#, python-format
msgid "Unable to destroy vbd %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:231
#, python-format
msgid "Error purging SR %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:233
#, python-format
msgid "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"
msgstr ""

#: nova/vnc/xvp_proxy.py:96 nova/vnc/xvp_proxy.py:101
#, python-format
msgid "Error in handshake: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:117
#, python-format
msgid "Invalid request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:137
#, python-format
msgid "Request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:140
#, python-format
msgid "Request made with missing token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:150
#, python-format
msgid "Request made with invalid token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:157
#, python-format
msgid "Unexpected error: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:177
#, python-format
msgid "Starting nova-xvpvncproxy node (version %s)"
msgstr ""

#: nova/volume/cinder.py:68
#, python-format
msgid "Cinderclient connection created using URL: %s"
msgstr ""

#: nova/volume/driver.py:103
#, python-format
msgid "Recovering from a failed execute.  Try number %s"
msgstr ""

#: nova/volume/driver.py:113
#, python-format
msgid "volume group %s doesn't exist"
msgstr ""

#: nova/volume/driver.py:324
#, python-format
msgid "Skipping ensure_export. No iscsi_target provisioned for volume: %s"
msgstr ""

#: nova/volume/driver.py:397
#, python-format
msgid "Skipping remove_export. No iscsi_target provisioned for volume: %s"
msgstr ""

#: nova/volume/driver.py:414
#, python-format
msgid ""
"Skipping remove_export. No iscsi_target is presently exported for volume:"
" %s"
msgstr ""

#: nova/volume/driver.py:423
msgid "ISCSI provider_location not stored, using discovery"
msgstr ""

#: nova/volume/driver.py:470
#, python-format
msgid "Could not find iSCSI export  for volume %s"
msgstr ""

#: nova/volume/driver.py:474
#, python-format
msgid "ISCSI Discovery: Found %s"
msgstr ""

#: nova/volume/driver.py:565
#, python-format
msgid "Cannot confirm exported volume id:%(volume_id)s."
msgstr ""

#: nova/volume/driver.py:606
#, python-format
msgid "FAKE ISCSI: %s"
msgstr ""

#: nova/volume/driver.py:618
#, python-format
msgid "rbd has no pool %s"
msgstr ""

#: nova/volume/driver.py:740
#, python-format
msgid "Image %s is not stored in rbd"
msgstr ""

#: nova/volume/driver.py:744
#, python-format
msgid "Image %s has blank components"
msgstr ""

#: nova/volume/driver.py:747
#, python-format
msgid "Image %s is not an rbd snapshot"
msgstr ""

#: nova/volume/driver.py:762
#, python-format
msgid "%s is in a different ceph cluster"
msgstr ""

#: nova/volume/driver.py:773
#, python-format
msgid "Unable to read image %s"
msgstr ""

#: nova/volume/driver.py:815
#, python-format
msgid "Sheepdog is not working: %s"
msgstr ""

#: nova/volume/driver.py:820
msgid "Sheepdog is not working"
msgstr ""

#: nova/volume/driver.py:924 nova/volume/driver.py:929
#, python-format
msgid "LoggingVolumeDriver: %s"
msgstr ""

#: nova/volume/iscsi.py:122
#, python-format
msgid "Creating volume: %s"
msgstr ""

#: nova/volume/iscsi.py:136
#, python-format
msgid "Failed to create iscsi target for volume id:%(vol_id)s."
msgstr ""

#: nova/volume/iscsi.py:146
#, python-format
msgid ""
"Failed to create iscsi target for volume id:%(vol_id)s. Please ensure "
"your tgtd config file contains 'include %(volumes_dir)s/*'"
msgstr ""

#: nova/volume/iscsi.py:154 nova/volume/iscsi.py:196
#, python-format
msgid "Removing volume: %s"
msgstr ""

#: nova/volume/iscsi.py:168
#, python-format
msgid "Failed to create iscsi target for volume id:%(volume_id)s."
msgstr ""

#: nova/volume/iscsi.py:177
msgid "valid iqn needed for show_target"
msgstr ""

