# Translations template for nova.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: nova\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-06-24 06:06+0000\n"
"PO-Revision-Date: 2014-06-20 16:41+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Japanese (http://www.transifex.com/projects/p/nova/language/"
"ja/)\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: nova/hooks.py:84
#, python-format
msgid "Fatal Exception running %(name)s pre-hook: %(obj)s"
msgstr ""

#: nova/hooks.py:89
#, python-format
msgid "Exception running %(name)s pre-hook: %(obj)s"
msgstr ""

#: nova/hooks.py:105
#, python-format
msgid "Fatal Exception running %(name)s post-hook: %(obj)s"
msgstr ""

#: nova/hooks.py:110
#, python-format
msgid "Exception running %(name)s post-hook: %(obj)s"
msgstr ""

#: nova/objects/instance_fault.py:86
msgid "Failed to notify cells of instance fault"
msgstr "インスタンスの障害をセルに通知できませんでした"

#: nova/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "除去される元の例外: %s"

#: nova/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "予期せぬ例外が、%d回()発生しました。再試行中。"

#: nova/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr "一定期間の呼び出しループ"

#: nova/openstack/common/loopingcall.py:136
msgid "in dynamic looping call"
msgstr "動的呼び出しループ"

#: nova/openstack/common/periodic_task.py:179
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr "%(full_task_name)s 中のエラー: %(e)s"

#: nova/openstack/common/policy.py:511
#, python-format
msgid "Failed to understand rule %s"
msgstr "ルール %s を解釈できませんでした"

#: nova/openstack/common/policy.py:521
#, python-format
msgid "No handler for matches of kind %s"
msgstr "種類 %s の一致向けのハンドラーがありません"

#: nova/openstack/common/policy.py:791
#, python-format
msgid "Failed to understand rule %r"
msgstr "ルール %r を解釈できませんでした"

#: nova/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "RPCクリーンアップ中に例外が発生"

#: nova/openstack/common/service.py:276
msgid "Unhandled exception"
msgstr "未処理例外"

#: nova/openstack/common/db/api.py:72
msgid "DB exceeded retry limit."
msgstr "DBへのリトライが上限に達しました。"

#: nova/openstack/common/db/api.py:76
msgid "DB connection error."
msgstr "DB接続エラーが発生しました。"

#: nova/openstack/common/db/sqlalchemy/session.py:460
msgid "DB exception wrapped."
msgstr "DB 例外がラップされました。"

#: nova/openstack/common/db/sqlalchemy/test_migrations.py:267
#, python-format
msgid "Failed to migrate to version %s on engine %s"
msgstr "バージョン%sをエンジン%sへの移行が失敗しました。"

#: nova/virt/libvirt/imagecache.py:130
#, python-format
msgid "Error reading image info file %(filename)s: %(error)s"
msgstr ""
"イメージ情報ファイル %(filename)s の読み取り中にエラーが発生しました: "
"%(error)s"

#: nova/virt/libvirt/imagecache.py:391
#, python-format
msgid "image %(id)s at (%(base_file)s): image verification failed"
msgstr "(%(base_file)s) にあるイメージ %(id)s: イメージの検査が失敗しました"

#: nova/virt/libvirt/imagecache.py:448
#, python-format
msgid "Failed to remove %(base_file)s, error was %(error)s"
msgstr "%(base_file)s の削除に失敗しました。エラーは %(error)s"

#: nova/virt/libvirt/lvm.py:201
#, python-format
msgid "ignoring unrecognized volume_clear='%s' value"
msgstr ""

#: nova/virt/libvirt/volume.py:141
#, python-format
msgid "Unknown content in connection_info/access_mode: %s"
msgstr ""
